export interface BerlinHouseVenue {
  id: number
  name: string
  area: string
  type: 'club' | 'bar'
  subgenres: string[]
  score: number
  cachet: string
  aforo: string
  entrada: string
  entrada_tipo: 'free' | 'low' | 'mid' | 'high'
  mejor: string
  ambiente: string
  reputacion: string
  contacto: string
  red_flag: string
  consejo: string
  instagram: string
}

export const BERLIN_HOUSE_VENUES: BerlinHouseVenue[] = [
  { id: 1, name: 'Watergate', area: 'Kreuzberg', type: 'club', subgenres: ['House','Deep House','Tech House'], score: 9.0, cachet: '€80–500', aforo: '600', entrada: '€10–15', entrada_tipo: 'mid', mejor: 'Fin de semana · terraza en verano', ambiente: 'Terrace sobre el río Spree. El mejor club de house en Berlín.', reputacion: 'Excelentes condiciones. Buenos pagadores. Abiertos a DJs europeos.', contacto: 'booking@water-gate.de', red_flag: '', consejo: 'Manda mix de afro/tech house. Revisa su lineup antes de escribir.', instagram: '@watergate_berlin' },
  { id: 2, name: 'Club der Visionaere', area: 'Treptow', type: 'club', subgenres: ['House','Deep House','Minimal House'], score: 8.8, cachet: '€60–300', aforo: '300', entrada: '€8–12', entrada_tipo: 'low', mejor: 'Domingo tarde (open air)', ambiente: 'Barcaza en el canal de Treptow. El mejor after de Berlín.', reputacion: 'Muy respetados en la escena house. Buenos con artistas que encajan.', contacto: 'booking@cdv.de o en persona', red_flag: '', consejo: 'Tu afro house y deep house encaja perfecto. El domingo tarde es su momento.', instagram: '@clubdervisionaere' },
  { id: 3, name: 'Ritter Butzke', area: 'Kreuzberg', type: 'club', subgenres: ['House','Soul House','Tech House'], score: 8.1, cachet: '€60–300', aforo: '700', entrada: '€8–12', entrada_tipo: 'low', mejor: 'Sábado', ambiente: 'Fábrica con varios pisos. Uno de los mejores clubs de house en Kreuzberg.', reputacion: 'Buenos pagadores. Abiertos a DJs con experiencia real.', contacto: 'booking@ritterbutzke.de', red_flag: '', consejo: 'Con experiencia y mixes sólidos, este venue es muy realista a corto plazo.', instagram: '@ritterbutzke' },
  { id: 4, name: 'Kater Blau', area: 'Mitte', type: 'club', subgenres: ['House','Deep House','Disco House'], score: 8.5, cachet: '€60–300', aforo: '500', entrada: '€10–16', entrada_tipo: 'mid', mejor: 'Fin de semana', ambiente: 'Club alternativo en el Spree. Ambiente muy artístico y relajado.', reputacion: 'Buenos con artistas. Conectado con la escena de arte de Berlín.', contacto: 'booking@katerblau.de', red_flag: '', consejo: 'La conexión con Dark Matter puede ser útil aquí.', instagram: '@katerblau' },
  { id: 5, name: 'About Blank', area: 'Friedrichshain', type: 'club', subgenres: ['House','Afro House','Queer House'], score: 8.5, cachet: '€50–280', aforo: '400', entrada: '€8–14', entrada_tipo: 'low', mejor: 'Viernes y sábado', ambiente: 'Club queer-friendly con jardín. Mezcla house, afro y experimental.', reputacion: 'Excelente trato a artistas. Muy inclusivos. Buenos pagadores.', contacto: 'booking@aboutblank.li', red_flag: '', consejo: 'Si tu set tiene dimensión queer o experimental, encajas muy bien.', instagram: '@aboutblank_berlin' },
  { id: 6, name: 'Treehouse Berlin', area: 'Friedrichshain', type: 'club', subgenres: ['Afro House','Deep House','Organic House'], score: 8.3, cachet: '€50–250', aforo: '400', entrada: '€8–14', entrada_tipo: 'low', mejor: 'Sábado', ambiente: 'Especializado en afro house y organic house. Nicho único en Berlín.', reputacion: 'Muy abiertos a DJs de afro house. Buenos pagadores para su tamaño.', contacto: 'booking@treehouseberlin.com o Instagram DM', red_flag: '', consejo: 'Con especialidad en afro house, es uno de los venues más alineados con tu sonido.', instagram: '@treehouseberlin' },
  { id: 7, name: 'Griessmuehle', area: 'Neukölln', type: 'club', subgenres: ['House','Tech House','Disco House'], score: 8.4, cachet: '€60–300', aforo: '800', entrada: '€8–14', entrada_tipo: 'low', mejor: 'Fin de semana', ambiente: 'Antigua fábrica en Neukölln. Escena muy house y diversa.', reputacion: 'Buenos pagadores. Abiertos a DJs con experiencia y sonido definido.', contacto: 'booking@griessmuehlebe.com', red_flag: '', consejo: 'Uno de los mejores venues de house en Neukölln. Muy asequible con mixes sólidos.', instagram: '@griessmuehlebe' },
  { id: 8, name: 'Anomalie Art Club', area: 'Prenzlauer Berg', type: 'club', subgenres: ['House','Afro House','Organic House'], score: 7.8, cachet: '€40–200', aforo: '300', entrada: '€6–12', entrada_tipo: 'low', mejor: 'Viernes y sábado', ambiente: 'Espacio artístico con programación de house y afro. Mezcla arte y música.', reputacion: 'Buenos con DJs que tienen componente artístico además del musical.', contacto: 'booking@anomalie-berlin.com o Instagram', red_flag: '', consejo: 'La conexión con Dark Matter es muy relevante aquí. Misma mezcla de arte y música.', instagram: '@anomalie_berlin' },
  { id: 9, name: 'PAX Berlin', area: 'Kreuzberg', type: 'bar', subgenres: ['Afro House','Afrobeats','House'], score: 7.9, cachet: '€30–150', aforo: '180', entrada: 'Gratis', entrada_tipo: 'free', mejor: 'Jueves, viernes y sábado', ambiente: 'Bar especializado en afro house y afrobeats. Nicho único en Berlín.', reputacion: 'Muy abiertos. Cachets modestos pero escena muy específica.', contacto: 'Instagram @pax.berlin o en persona', red_flag: '', consejo: 'Con especialidad en afro house, PAX es uno de los más alineados con tu sonido.', instagram: '@pax.berlin' },
  { id: 10, name: 'Monarch Bar', area: 'Kreuzberg', type: 'bar', subgenres: ['House','Indie House','Mixed'], score: 7.5, cachet: '€30–120', aforo: '150', entrada: 'Gratis', entrada_tipo: 'free', mejor: 'Jueves y viernes', ambiente: 'Bar encima de un supermercado turco. Ambiente muy Berlín.', reputacion: 'Cachets bajos pero muy abiertos. Buen lugar para volver a tocar.', contacto: 'info@monarchbar.de o en persona', red_flag: '', consejo: 'Ideal para el primer booking de regreso. Sin presión, ambiente relajado.', instagram: '@monarchbar' },
  { id: 11, name: 'Neue Heimat', area: 'Wedding', type: 'bar', subgenres: ['House','Disco','Funk'], score: 7.2, cachet: '€20–80', aforo: '120', entrada: 'Gratis', entrada_tipo: 'free', mejor: 'Viernes noche', ambiente: 'Bar cultural en Wedding. Sin turistas. Ambiente muy local y alternativo.', reputacion: 'Pagan poco pero son honestos. Muy community y abiertos a DJs con criterio.', contacto: 'Instagram @neueheimat o en persona', red_flag: '', consejo: 'Excelente para hacer red en la escena local de Berlín.', instagram: '@neueheimat' },
  { id: 12, name: 'Klunkerkranich', area: 'Neukölln', type: 'bar', subgenres: ['House','Deep House','Disco'], score: 7.4, cachet: '€30–120', aforo: '250', entrada: '€3–5', entrada_tipo: 'low', mejor: 'Verano (terraza open air)', ambiente: 'Bar en azotea de centro comercial en Neukölln. Terraza open air con vistas.', reputacion: 'Muy accesibles para DJs que vuelven. Ambiente muy relajado.', contacto: 'Instagram @klunkerkranich o en persona', red_flag: '', consejo: 'La terraza en verano es mágica. Uno de los primeros que contactaría.', instagram: '@klunkerkranich' },
  { id: 13, name: 'Sisyphos', area: 'Lichtenberg', type: 'club', subgenres: ['House','Tech House','Mixed'], score: 8.7, cachet: '€60–350', aforo: '3000', entrada: '€8–12', entrada_tipo: 'low', mejor: 'Domingo tarde (marathon sets)', ambiente: 'Complejo industrial de 72h. Varios stages. Muy community.', reputacion: 'Pagan correcto. Stages secundarios perfectos para DJs volviendo.', contacto: 'booking@sisyphos-berlin.de', red_flag: '', consejo: 'Propón empezar en el stage Hof. Con tu experiencia te diferencias.', instagram: '@sisyphos_berlin' },
  { id: 14, name: 'Mensch Meier', area: 'Friedrichshain', type: 'club', subgenres: ['House','Soul','Funk House'], score: 7.6, cachet: '€40–180', aforo: '350', entrada: '€5–10', entrada_tipo: 'low', mejor: 'Viernes y sábado', ambiente: 'Club cultural en Friedrichshain. House con influencias de soul y funk.', reputacion: 'Muy abiertos a DJs con propuesta musical propia.', contacto: 'booking@mensch-meier.com', red_flag: '', consejo: 'Si haces house con influencias de soul o funk, encaja muy bien.', instagram: '@mensch_meier_berlin' },
  { id: 15, name: 'Revier Südost', area: 'Treptow', type: 'bar', subgenres: ['House','Tech House','Mixed'], score: 7.0, cachet: '€20–100', aforo: '200', entrada: '€2–5', entrada_tipo: 'low', mejor: 'Viernes y sábado', ambiente: 'Bar industrial en Treptow. Muy abierto a propuestas.', reputacion: 'Cachets bajos pero muy abiertos a DJs con experiencia.', contacto: 'Instagram @reviersudost', red_flag: '', consejo: 'Buena opción para primeros bookings de regreso. Sin exigencias.', instagram: '@reviersudost' },
]

export const BERLIN_HOUSE_STATS = {
  total: BERLIN_HOUSE_VENUES.length,
  clubs: BERLIN_HOUSE_VENUES.filter(v => v.type === 'club').length,
  bars: BERLIN_HOUSE_VENUES.filter(v => v.type === 'bar').length,
  free_entry: BERLIN_HOUSE_VENUES.filter(v => v.entrada_tipo === 'free').length,
}
