// ================================================
// DJBOOK PRO — Base de datos de venues europeos
// ~200 venues en 18 ciudades
// ================================================

export interface VenueDB {
  id: number
  name: string
  city: string
  country: string
  area: string
  type: 'club' | 'bar' | 'festival'
  genres: string[]
  score: number
  cachet: string
  aforo: string
  fundado: string
  entrada_precio: string
  entrada_tipo: 'free' | 'low' | 'mid' | 'high'
  entrada_nota: string
  ambiente: string
  reputacion: string
  artistas: string
  contacto: string
  red_flag: string
  consejo: string
  mejor: string
  website?: string
  instagram?: string
}

export const VENUES_DB: VenueDB[] = [

  // ─────────────────────────────────────────────
  // BERLÍN
  // ─────────────────────────────────────────────
  { id: 1, name: 'Berghain', city: 'Berlín', country: 'Alemania', area: 'Friedrichshain', type: 'club', genres: ['Techno', 'Industrial'], score: 9.8, cachet: '€150–800', aforo: '1500', fundado: '2004', entrada_precio: '€15–20', entrada_tipo: 'high', entrada_nota: 'Precio variable. La cola puede durar horas. Sin garantía de entrada.', ambiente: 'La catedral del techno mundial. Ambiente oscuro, dress code estricto, sets de 6-8h.', reputacion: 'Pagan bien y a tiempo. Contratos claros. El estándar de la industria.', artistas: 'Ben Klock, Len Faki, Marcel Dettmann', contacto: 'Solo por recomendación directa o representante.', red_flag: '', consejo: 'No contactes directamente. Necesitas un agente o que un residente te recomiende.', mejor: 'Viernes noche – domingo tarde', instagram: '@berghain_berlin' },
  { id: 2, name: 'Tresor', city: 'Berlín', country: 'Alemania', area: 'Mitte', type: 'club', genres: ['Techno', 'Detroit Techno'], score: 9.2, cachet: '€100–600', aforo: '800', fundado: '1991', entrada_precio: '€12–18', entrada_tipo: 'mid', entrada_nota: 'Precio estándar para Berlín. Sin dress code estricto.', ambiente: 'Club histórico en bunker subterráneo. El techno más duro de Berlín.', reputacion: 'Institución. Pagan correctamente. Valoran la autenticidad artística.', artistas: 'DVS1, Surgeon, Planetary Assault Systems', contacto: 'booking@tresorberlin.com — presenta tu SoundCloud y mix.', red_flag: '', consejo: 'Envía un mix de mínimo 1h en la línea Tresor. Sin concesiones comerciales.', mejor: 'Viernes y sábado madrugada', website: 'tresorberlin.com' },
  { id: 3, name: 'Watergate', city: 'Berlín', country: 'Alemania', area: 'Kreuzberg', type: 'club', genres: ['House', 'Techno', 'Deep House'], score: 8.9, cachet: '€80–500', aforo: '600', fundado: '2002', entrada_precio: '€10–15', entrada_tipo: 'mid', entrada_nota: 'Más accesible que otros clubs top de Berlín.', ambiente: 'Club con terraza al río Spree. Equilibrio perfecto entre house y techno.', reputacion: 'Buenos pagadores. Abiertos a nuevos DJs con buen material.', artistas: 'Maceo Plex, Dixon, Âme', contacto: 'booking@water-gate.de — incluye bio, mix y links.', red_flag: '', consejo: 'Tu estilo debe encajar entre house y techno. Revisa su lineup reciente.', mejor: 'Fin de semana, terraza en verano', website: 'water-gate.de' },
  { id: 4, name: 'Sisyphos', city: 'Berlín', country: 'Alemania', area: 'Lichtenberg', type: 'club', genres: ['House', 'Techno', 'Mixed'], score: 8.7, cachet: '€60–350', aforo: '3000', fundado: '2013', entrada_precio: '€8–12', entrada_tipo: 'low', entrada_nota: 'Precio bajo para el tamaño. Fiestas de 72h el fin de semana.', ambiente: 'Antiguo complejo industrial. Fiesta de 72h los fines de semana. Muy community.', reputacion: 'Pagan correcto. Gran oportunidad para DJs emergentes en stages secundarios.', artistas: 'Marquis Hawkes, Lena Willikens', contacto: 'booking@sisyphos-berlin.de', red_flag: 'El stage principal es difícil. Empieza por los stages pequeños.', consejo: 'Ideal para DJs nuevos. Propón comenzar en el stage Hof o Pferdestall.', mejor: 'Domingo tarde (marathon sets)' },
  { id: 5, name: 'About Blank', city: 'Berlín', country: 'Alemania', area: 'Friedrichshain', type: 'club', genres: ['Techno', 'Experimental', 'Queer'], score: 8.5, cachet: '€50–300', aforo: '400', fundado: '2010', entrada_precio: '€8–14', entrada_tipo: 'low', entrada_nota: 'Accesible. Algunas noches queer tienen precio reducido.', ambiente: 'Club alternativo y queer-friendly. Jardín enorme. Ambiente muy community.', reputacion: 'Excelente trato a artistas. Muy inclusivos. Pagan bien para su tamaño.', artistas: 'Objekt, Hunee, Special Request', contacto: 'booking@aboutblank.li', red_flag: '', consejo: 'Prioriza si tu música tiene dimensión política o queer.', mejor: 'Viernes queer, sábado techno' },
  { id: 6, name: 'Ohm', city: 'Berlín', country: 'Alemania', area: 'Mitte', type: 'club', genres: ['Techno', 'Experimental'], score: 8.6, cachet: '€80–400', aforo: '300', fundado: '2016', entrada_precio: '€12–16', entrada_tipo: 'mid', entrada_nota: 'En Kraftwerk Berlin. Precio justo para la calidad acústica.', ambiente: 'Club en Kraftwerk Berlin. Acústica perfecta. Muy artístico y serio.', reputacion: 'Excelentes condiciones para artistas. Muy profesionales.', artistas: 'Shackleton, Actress, Burial', contacto: 'booking@ohm-berlin.com', red_flag: '', consejo: 'Si haces techno experimental o club music seria, es tu sitio.', mejor: 'Viernes' },
  { id: 7, name: 'Monarch Bar', city: 'Berlín', country: 'Alemania', area: 'Kreuzberg', type: 'bar', genres: ['House', 'Indie', 'Mixed'], score: 7.5, cachet: '€30–120', aforo: '150', fundado: '2005', entrada_precio: 'Gratis', entrada_tipo: 'free', entrada_nota: 'Sin entrada. Consumición mínima algunos días.', ambiente: 'Bar con cabina encima de un supermercado turco. Atmosférico y peculiar.', reputacion: 'Pagan poco pero es buen lugar para empezar. Muy chill.', artistas: 'DJs locales emergentes', contacto: 'info@monarchbar.de o directo en persona', red_flag: '', consejo: 'Ideal para primer booking pagado en Berlín.', mejor: 'Jueves y viernes' },
  { id: 8, name: 'Ritter Butzke', city: 'Berlín', country: 'Alemania', area: 'Kreuzberg', type: 'club', genres: ['House', 'Techno', 'Soul'], score: 8.1, cachet: '€60–300', aforo: '700', fundado: '2007', entrada_precio: '€8–12', entrada_tipo: 'low', entrada_nota: 'Precio accesible. Buena relación calidad-precio.', ambiente: 'Club en fábrica con varios pisos. Equilibrio entre techno y house.', reputacion: 'Buenos pagadores. Abiertos a DJs internacionales nuevos.', artistas: 'Âme, Chaim, Tama Sumo', contacto: 'booking@ritterbutzke.de — incluye SoundCloud y bio.', red_flag: '', consejo: 'Buen punto de entrada al circuito serio de Berlín.', mejor: 'Sábado' },
  { id: 9, name: 'Panorama Bar', city: 'Berlín', country: 'Alemania', area: 'Friedrichshain', type: 'club', genres: ['House', 'Electro'], score: 9.5, cachet: '€120–700', aforo: '800', fundado: '2004', entrada_precio: '€15–20', entrada_tipo: 'high', entrada_nota: 'Mismo edificio que Berghain, planta superior. Entrada conjunta.', ambiente: 'Planta superior del Berghain. House y electro. Luz natural por las mañanas.', reputacion: 'Igual que Berghain: profesionales y bien pagadores.', artistas: 'Honey Dijon, Peggy Gou, Prosumer', contacto: 'Mismo proceso que Berghain. Solo por agente.', red_flag: '', consejo: 'Si haces house, este es tu objetivo en Berghain. Mismo proceso de booking.', mejor: 'Sábado madrugada – domingo mañana' },
  { id: 51, name: 'Klubnacht KitKatClub', city: 'Berlín', country: 'Alemania', area: 'Mitte', type: 'club', genres: ['Techno', 'Fetish', 'Experimental'], score: 8.4, cachet: '€60–300', aforo: '600', fundado: '1994', entrada_precio: '€12–20', entrada_tipo: 'mid', entrada_nota: 'Dress code muy estricto (fetish o creativo).', ambiente: 'Club fetish icónico de Berlín. Ambiente muy liberado y underground.', reputacion: 'Buenos pagadores. Ambiente único en Europa.', artistas: 'DJs de techno y fetish berlineses', contacto: 'booking@kitkatclub.org', red_flag: 'El dress code es innegociable. Sin ropa conservadora.', consejo: 'Si vas, investiga el dress code antes. Muy específico y serio.', mejor: 'Sábado (Klubnacht)', website: 'kitkatclub.org' },
  { id: 52, name: 'Griessmühle', city: 'Berlín', country: 'Alemania', area: 'Neukölln', type: 'club', genres: ['Techno', 'House', 'Experimental'], score: 8.3, cachet: '€50–250', aforo: '500', fundado: '2016', entrada_precio: '€8–12', entrada_tipo: 'low', entrada_nota: 'Precio accesible. Open air en verano.', ambiente: 'Club en antigua fábrica con jardín. Escena muy underground y comunitaria.', reputacion: 'Muy abiertos a artistas emergentes. Ambiente sin egos.', artistas: 'Lena Willikens, Vladimir Ivkovic', contacto: 'booking@griessmühle.de', red_flag: '', consejo: 'Buena oportunidad para DJs emergentes. Propón ideas de eventos.', mejor: 'Fin de semana y eventos especiales de verano' },
  { id: 53, name: 'Chalet Berlin', city: 'Berlín', country: 'Alemania', area: 'Treptow', type: 'club', genres: ['Techno', 'House', 'Minimal'], score: 8.2, cachet: '€60–300', aforo: '800', fundado: '2011', entrada_precio: '€10–15', entrada_tipo: 'mid', entrada_nota: 'Club con jardín en antiguo chalet soviético.', ambiente: 'Antigua villa soviética con jardín enorme. Ambiente muy especial y bohemio.', reputacion: 'Buenos con artistas. Escena muy auténtica.', artistas: 'Gerd Janson, Joris Voorn, Tama Sumo', contacto: 'info@chalet.berlin', red_flag: '', consejo: 'Revisa los eventos del jardín en verano. Muy buenos y más accesibles.', mejor: 'Verano: jardín. Invierno: fin de semana' },
  { id: 54, name: 'Club der Visionaere', city: 'Berlín', country: 'Alemania', area: 'Treptow', type: 'bar', genres: ['House', 'Minimal', 'Deep House'], score: 8.6, cachet: '€40–200', aforo: '200', fundado: '1997', entrada_precio: '€5–10', entrada_tipo: 'low', entrada_nota: 'Pontón en el canal. Solo en verano.', ambiente: 'Pontón minimalista en el canal. La mañana del domingo es legendaria.', reputacion: 'Muy respetado. Residentes muy buenos. Sin pretensiones.', artistas: 'Zip, Dj T., Âme', contacto: 'info@cdv-berlin.de', red_flag: '', consejo: 'El domingo por la mañana es el momento más icónico. Asistir es networking.', mejor: 'Domingo mañana (post Berghain)' },
  { id: 55, name: 'Wilde Renate', city: 'Berlín', country: 'Alemania', area: 'Friedrichshain', type: 'club', genres: ['House', 'Techno', 'Disco'], score: 7.9, cachet: '€40–200', aforo: '400', fundado: '2007', entrada_precio: '€8–12', entrada_tipo: 'low', entrada_nota: 'Antigua villa con múltiples habitaciones temáticas.', ambiente: 'Club en antigua villa con decoración muy peculiar por habitaciones.', reputacion: 'Buenos con DJs nuevos. Ambiente muy relajado y comunitario.', artistas: 'DJs locales de house y techno', contacto: 'info@wilderenate.de', red_flag: '', consejo: 'Buena opción para DJs en etapa inicial en Berlín.', mejor: 'Sábado' },
  { id: 56, name: 'RSO Berlin', city: 'Berlín', country: 'Alemania', area: 'Neukölln', type: 'club', genres: ['Techno', 'Experimental', 'Club Music'], score: 8.0, cachet: '€50–250', aforo: '300', fundado: '2020', entrada_precio: '€8–14', entrada_tipo: 'low', entrada_nota: 'Club nuevo en Neukölln. Escena muy forward-thinking.', ambiente: 'Club nuevo con programación muy experimental. La nueva guardia de Berlín.', reputacion: 'Muy abiertos a propuestas nuevas. Buenos pagadores para su tamaño.', artistas: 'Artistas experimentales y emergentes', contacto: 'booking@rso.berlin', red_flag: '', consejo: 'Ideal si tu música es experimental o forward-thinking.', mejor: 'Viernes y sábado' },
  { id: 57, name: 'Ipse Berlin', city: 'Berlín', country: 'Alemania', area: 'Treptow', type: 'club', genres: ['House', 'Techno', 'Afro', 'Disco'], score: 8.1, cachet: '€50–250', aforo: '600', fundado: '2014', entrada_precio: '€8–14', entrada_tipo: 'low', entrada_nota: 'Club en barco con terraza en el canal. Solo temporada verano.', ambiente: 'Club en barco con terraza en el río. Ambiente muy positivo y diverso.', reputacion: 'Buenos pagadores. Muy abiertos a géneros distintos al techno duro.', artistas: 'Red Axes, Hunee, Gilles Peterson', contacto: 'booking@ipse.berlin', red_flag: '', consejo: 'Si haces afro, disco o house ecléctico, Ipse es perfecto.', mejor: 'Temporada verano (may-sep)' },

  // ─────────────────────────────────────────────
  // MADRID
  // ─────────────────────────────────────────────
  { id: 10, name: 'Fabrik', city: 'Madrid', country: 'España', area: 'Fuenlabrada', type: 'club', genres: ['Techno', 'Trance', 'Hard Dance'], score: 8.8, cachet: '€200–1500', aforo: '5000', fundado: '2002', entrada_precio: '€12–20', entrada_tipo: 'mid', entrada_nota: 'Precio variable según artista. Abonos de temporada disponibles.', ambiente: 'El club más grande de España. Sonido brutal. Shows de producción visual.', reputacion: 'Buenos pagadores. Muy profesionales. Producción de primer nivel.', artistas: 'Richie Hawtin, Carl Cox, Amelie Lens', contacto: 'booking@fabricmadrid.com', red_flag: '', consejo: 'Difícil para DJs nuevos en el escenario principal. Busca eventos secundarios.', mejor: 'Sábado noche', website: 'fabricmadrid.com' },
  { id: 11, name: 'Sala Charada', city: 'Madrid', country: 'España', area: 'Centro', type: 'club', genres: ['House', 'Techno', 'Minimal'], score: 7.8, cachet: '€80–350', aforo: '400', fundado: '2015', entrada_precio: '€8–15', entrada_tipo: 'low', entrada_nota: 'Precio accesible. Listas hasta las 2am gratuitas.', ambiente: 'Sala mediana en el centro. Sonido bueno, ambiente sin pretensiones.', reputacion: 'Pagan correctamente. Buenos con DJs nuevos con potencial.', artistas: 'DJs locales y europeos emergentes', contacto: 'booking@salacharda.com', red_flag: '', consejo: 'Buena puerta de entrada a la escena de Madrid. Manda mix + bio.', mejor: 'Viernes y sábado' },
  { id: 12, name: 'Teatro Kapital', city: 'Madrid', country: 'España', area: 'Atocha', type: 'club', genres: ['Commercial', 'House', 'Hip-Hop'], score: 6.5, cachet: '€100–500', aforo: '2000', fundado: '1994', entrada_precio: '€15–25', entrada_tipo: 'high', entrada_nota: '7 plantas temáticas. Precio incluye consumición.', ambiente: 'Mega club comercial en edificio teatral histórico. 7 pisos de música.', reputacion: 'Pagan bien pero el ambiente es muy comercial.', artistas: 'DJs comerciales y celebrities', contacto: 'booking@grupo-kapital.com', red_flag: 'Muy comercial. No recomendable para DJs de electrónica seria.', consejo: 'Solo si haces música comercial o eres DJ residente de eventos privados.', mejor: 'Jueves, viernes y sábado' },
  { id: 13, name: 'Mondo Disko', city: 'Madrid', country: 'España', area: 'Malasaña', type: 'club', genres: ['Disco', 'House', 'Funk'], score: 8.0, cachet: '€60–250', aforo: '300', fundado: '2010', entrada_precio: '€6–10', entrada_tipo: 'low', entrada_nota: 'Muy accesible. Precio reducido en lista.', ambiente: 'Club disco-house en Malasaña. Ambiente muy divertido y colorido.', reputacion: 'Buenos con artistas. Ambiente muy festivo y sin egos.', artistas: 'DJs de disco y funk nacionales e internacionales', contacto: 'info@mondodisko.com o Instagram', red_flag: '', consejo: 'Perfecto si haces disco, funk o nu-disco. Ambiente muy receptivo.', mejor: 'Viernes noche', instagram: '@mondodisko' },
  { id: 14, name: 'Bahnhof Oost', city: 'Madrid', country: 'España', area: 'Lavapiés', type: 'bar', genres: ['Techno', 'House', 'Experimental'], score: 7.6, cachet: '€30–100', aforo: '100', fundado: '2016', entrada_precio: 'Gratis', entrada_tipo: 'free', entrada_nota: 'Sin entrada. Bar alternativo de barrio.', ambiente: 'Bar alternativo en Lavapiés. Escena underground madrileña.', reputacion: 'Cachets bajos pero muy abiertos. Buenos para la escena local.', artistas: 'DJs emergentes del underground madrileño', contacto: 'Instagram @bahnhof_oost_madrid', red_flag: '', consejo: 'Ideal para hacer red en la escena underground de Madrid.', mejor: 'Jueves y viernes' },
  { id: 61, name: 'Space of Sound Madrid', city: 'Madrid', country: 'España', area: 'Entrevías', type: 'club', genres: ['Techno', 'Trance', 'Hard Techno'], score: 8.2, cachet: '€100–600', aforo: '3000', fundado: '2001', entrada_precio: '€12–20', entrada_tipo: 'mid', entrada_nota: 'Gran club madrileño. Segundo en tamaño tras Fabrik.', ambiente: 'Mega club al sur de Madrid. Producción visual grande. Escena techno dura.', reputacion: 'Buenos pagadores. Producción seria. Abiertos a artistas con nombre regional.', artistas: 'Paul van Dyk, Wehbba, Enrico Sangiuliano', contacto: 'booking@spaceofound.com', red_flag: '', consejo: 'Si haces techno oscuro o trance progresivo, este es tu club en Madrid.', mejor: 'Sábado' },
  { id: 62, name: 'Ochoymedio Club', city: 'Madrid', country: 'España', area: 'Callao', type: 'club', genres: ['Indie', 'Electronic', 'Alternative'], score: 7.9, cachet: '€50–200', aforo: '350', fundado: '2000', entrada_precio: '€8–12', entrada_tipo: 'low', entrada_nota: 'Sala indie-electrónica en pleno centro.', ambiente: 'Club alternativo en el centro. Mezcla indie y electrónica alternativa.', reputacion: 'Buenos con artistas alternativos. Ambiente muy creativo y abierto.', artistas: 'DJs y bandas de indie electrónico', contacto: 'booking@ochoymedio.net', red_flag: '', consejo: 'Si tienes propuesta alternativa o indie-electrónica, es un gran sitio.', mejor: 'Viernes' },
  { id: 63, name: 'La Riviera Madrid', city: 'Madrid', country: 'España', area: 'Puente de Segovia', type: 'club', genres: ['Electronic', 'House', 'Techno', 'Live'], score: 8.3, cachet: '€150–1000', aforo: '2000', fundado: '1984', entrada_precio: '€12–25', entrada_tipo: 'mid', entrada_nota: 'Precio variable según artista. Sala multiusos.', ambiente: 'Sala de referencia para conciertos y clubbing en Madrid. Orillas del Manzanares.', reputacion: 'Muy profesionales. Buenos pagadores. Producciones de nivel.', artistas: 'Variado — house, techno y live acts internacionales', contacto: 'booking@salariviera.com', red_flag: '', consejo: 'Buena sala para DJ sets con componente live o actos más grandes.', mejor: 'Viernes y sábado' },

  // ─────────────────────────────────────────────
  // BARCELONA
  // ─────────────────────────────────────────────
  { id: 15, name: 'Razzmatazz', city: 'Barcelona', country: 'España', area: 'Poblenou', type: 'club', genres: ['Indie', 'Techno', 'House', 'Pop'], score: 8.4, cachet: '€100–600', aforo: '3000', fundado: '2000', entrada_precio: '€10–20', entrada_tipo: 'mid', entrada_nota: '5 salas con música diferente. Precio variable según evento.', ambiente: '5 salas en antigua fábrica. La sala más grande de Barcelona.', reputacion: 'Muy profesionales. Buenos pagadores. Producción de primer nivel.', artistas: 'Variado — todos los géneros', contacto: 'booking@razzmatazz.com', red_flag: '', consejo: 'Presenta tu propuesta especificando en qué sala encajas mejor.', mejor: 'Viernes y sábado', website: 'salarazzmatazz.com' },
  { id: 16, name: 'Input Barcelona', city: 'Barcelona', country: 'España', area: 'Poble Sec', type: 'club', genres: ['Techno', 'House', 'Minimal'], score: 9.0, cachet: '€80–500', aforo: '500', fundado: '2015', entrada_precio: '€10–18', entrada_tipo: 'mid', entrada_nota: 'Sistema de sonido Funktion-One. Precio acorde a la calidad.', ambiente: 'El mejor sistema de sonido de Barcelona. Club serio y artístico.', reputacion: 'Excelentes condiciones para artistas. Muy respetados en la escena.', artistas: 'Surgeon, Paula Temple, Objekt', contacto: 'booking@inputbcn.com', red_flag: '', consejo: 'Si haces techno serio, este es tu objetivo en Barcelona.', mejor: 'Viernes y sábado', website: 'inputbcn.com' },
  { id: 17, name: 'Nitsa Club', city: 'Barcelona', country: 'España', area: 'Nou de la Rambla', type: 'club', genres: ['Techno', 'House', 'Electronic'], score: 8.7, cachet: '€70–400', aforo: '600', fundado: '1993', entrada_precio: '€8–15', entrada_tipo: 'low', entrada_nota: 'Veterano. Precio muy accesible para la calidad del lineup.', ambiente: 'Club histórico en sala Apolo. Uno de los más respetados de España.', reputacion: 'Institución. Pagan bien. Cuidan mucho la programación artística.', artistas: 'Dixon, Âme, Hunee, Job Jobse', contacto: 'info@nitsa.com', red_flag: '', consejo: 'Envía mix muy cuidado. Valoran la coherencia artística por encima de todo.', mejor: 'Sábado madrugada', website: 'nitsa.com' },
  { id: 18, name: 'Moog Barcelona', city: 'Barcelona', country: 'España', area: 'Barrio Gótico', type: 'club', genres: ['Techno', 'Electronic', 'Industrial'], score: 8.2, cachet: '€50–250', aforo: '250', fundado: '1994', entrada_precio: '€7–12', entrada_tipo: 'low', entrada_nota: 'Club íntimo y accesible. Muy popular entre locales.', ambiente: 'Club pequeño y oscuro en el Barrio Gótico. Muy íntimo y underground.', reputacion: 'Buenos con artistas. Ambiente muy auténtico.', artistas: 'DJs de techno y electronic europeos', contacto: 'info@masimas.com (grupo Mas i Mas)', red_flag: '', consejo: 'Buena opción para DJs con estética underground. Envía mix oscuro.', mejor: 'Jueves y sábado' },
  { id: 68, name: 'Sala Apolo', city: 'Barcelona', country: 'España', area: 'Nou de la Rambla', type: 'club', genres: ['Electronic', 'House', 'Indie', 'Live'], score: 8.5, cachet: '€80–500', aforo: '1200', fundado: '1943', entrada_precio: '€10–20', entrada_tipo: 'mid', entrada_nota: 'Sala histórica. Alberga Nitsa Club los sábados.', ambiente: 'Sala histórica modernista. Muy versátil y con una historia enorme.', reputacion: 'Institución. Muy profesionales. Buena reputación en la escena.', artistas: 'Variado — Nitsa (house/techno) y otros géneros', contacto: 'booking@sala-apolo.com', red_flag: '', consejo: 'La sala principal es grande. Contacta también para eventos de Nitsa si haces house.', mejor: 'Sábado (Nitsa) y viernes', website: 'sala-apolo.com' },
  { id: 69, name: 'Laut Barcelona', city: 'Barcelona', country: 'España', area: 'Gràcia', type: 'club', genres: ['Techno', 'House', 'Experimental'], score: 8.1, cachet: '€60–300', aforo: '400', fundado: '2019', entrada_precio: '€8–15', entrada_tipo: 'low', entrada_nota: 'Club nuevo con programación muy cuidada en Gràcia.', ambiente: 'Club artístico en Gràcia. Muy serio en la programación y el sonido.', reputacion: 'Muy abiertos a artistas europeos emergentes con propuesta.', artistas: 'DJs de techno y house europeos emergentes', contacto: 'booking@lautbcn.com', red_flag: '', consejo: 'Uno de los mejores clubs nuevos de Barcelona. Manda propuesta artística.', mejor: 'Viernes y sábado' },
  { id: 70, name: 'Macarena Club', city: 'Barcelona', country: 'España', area: 'Barrio Gótico', type: 'bar', genres: ['House', 'Minimal', 'Deep House'], score: 7.8, cachet: '€30–150', aforo: '100', fundado: '2004', entrada_precio: '€5–8', entrada_tipo: 'low', entrada_nota: 'Bar-club pequeñísimo. Entrada gratuita muchos días.', ambiente: 'El bar-club más pequeño de Barcelona. Muy íntimo y underground.', reputacion: 'Ambiente legendario. Cachets bajos pero muy valorado en la escena.', artistas: 'DJs locales de deep house y minimal', contacto: 'info@macarenaclub.com', red_flag: '', consejo: 'Icónico por su tamaño y ambiente. Ideal para networking en Barcelona.', mejor: 'Jueves, viernes y sábado' },
  { id: 72, name: 'Marula Café', city: 'Barcelona', country: 'España', area: 'Barrio Gótico', type: 'bar', genres: ['House', 'Funk', 'Soul', 'Afro'], score: 8.0, cachet: '€30–150', aforo: '200', fundado: '2005', entrada_precio: '€5–10', entrada_tipo: 'low', entrada_nota: 'Ambiente afro y house cálido. Sin pretensiones.', ambiente: 'Bar-club con programación afro, house y funk. Muy community.', reputacion: 'Buenos con artistas de afro y funk. Muy abiertos.', artistas: 'DJs de afro house, funk y soul', contacto: 'info@marulacafe.com', red_flag: '', consejo: 'Si haces afro house o afrobeat, este es tu sitio en Barcelona.', mejor: 'Jueves y sábado' },

  // ─────────────────────────────────────────────
  // IBIZA
  // ─────────────────────────────────────────────
  { id: 20, name: 'DC-10', city: 'Ibiza', country: 'España', area: 'Playa den Bossa', type: 'club', genres: ['House', 'Techno', 'Organic'], score: 9.6, cachet: '€200–2000', aforo: '1200', fundado: '1999', entrada_precio: '€20–40', entrada_tipo: 'high', entrada_nota: 'Lunes es el día icónico (Circoloco). Precio alto en verano.', ambiente: 'El club más auténtico de Ibiza. Terrace legendaria al aire libre.', reputacion: 'Los mejores de la isla en trato a artistas. Contratos serios.', artistas: 'Seth Troxler, Loco Dice, The Martinez Brothers', contacto: 'booking@dc10ibiza.com', red_flag: '', consejo: 'Solo en verano (jun-oct). Necesitas representación o recomendación directa.', mejor: 'Lunes (Circoloco)', website: 'dc10ibiza.com' },
  { id: 21, name: 'Amnesia Ibiza', city: 'Ibiza', country: 'España', area: 'San Rafael', type: 'club', genres: ['House', 'Techno', 'Commercial'], score: 8.9, cachet: '€300–3000', aforo: '3000', fundado: '1976', entrada_precio: '€30–60', entrada_tipo: 'high', entrada_nota: 'Uno de los clubs más caros de Ibiza. Espectáculos visuales.', ambiente: 'Mega club histórico. La sala principal tiene el techo que se abre.', reputacion: 'Buenos pagadores para artistas con nombre. Producciones espectaculares.', artistas: 'Marco Carola, Luciano, Carl Cox', contacto: 'booking@amnesia.es', red_flag: 'Muy difícil para nuevos. Orientado a artistas establecidos.', consejo: 'Orientado a artistas con booking internacional. Necesitas agencia.', mejor: 'Martes y jueves (eventos residentes)', website: 'amnesia.es' },
  { id: 22, name: 'Pacha Ibiza', city: 'Ibiza', country: 'España', area: 'Ibiza Ciudad', type: 'club', genres: ['House', 'Commercial', 'Deep House'], score: 8.5, cachet: '€400–5000', aforo: '3000', fundado: '1973', entrada_precio: '€30–70', entrada_tipo: 'high', entrada_nota: 'El más icónico de Ibiza. Precios premium.', ambiente: 'El club más famoso del mundo. Icono absoluto de la isla.', reputacion: 'Pagan muy bien a artistas establecidos. Contratos profesionales.', artistas: 'David Guetta, Solomun, Black Coffee', contacto: 'booking@pacha.com', red_flag: 'Solo para artistas con nombre internacional. Imposible para nuevos.', consejo: 'Target a largo plazo. Necesitas agencia consolidada y nombre propio.', mejor: 'Viernes (Solomun+1)', website: 'pacha.com' },
  { id: 23, name: 'Hï Ibiza', city: 'Ibiza', country: 'España', area: 'Playa den Bossa', type: 'club', genres: ['House', 'Techno', 'Commercial'], score: 8.7, cachet: '€300–4000', aforo: '2500', fundado: '2017', entrada_precio: '€25–55', entrada_tipo: 'high', entrada_nota: 'Club moderno con producción visual de primer nivel.', ambiente: 'El club más moderno de Ibiza. Tecnología visual avanzada.', reputacion: 'Muy profesionales. Buenos con artistas internacionales.', artistas: 'Eric Prydz, Tale Of Us, Fisher', contacto: 'booking@hiibiza.com', red_flag: 'Para artistas establecidos. Muy difícil para nuevos.', consejo: 'Necesitas agencia internacional. Target a largo plazo.', mejor: 'Miércoles y domingos' },
  { id: 125, name: 'Eden Ibiza', city: 'Ibiza', country: 'España', area: 'San Antonio', type: 'club', genres: ['House', 'Techno', 'Commercial'], score: 7.9, cachet: '€200–2000', aforo: '3000', fundado: '1999', entrada_precio: '€20–40', entrada_tipo: 'high', entrada_nota: 'Mega club en San Antonio. Muy renovado.', ambiente: 'Mega club renovado en San Antonio. Buen equilibrio entre comercial y underground.', reputacion: 'Buenos pagadores. Más accesible que Pacha o Amnesia para nuevos.', artistas: 'Hot Since 82, Cristian Varela, Sidney Charles', contacto: 'booking@edenibiza.com', red_flag: '', consejo: 'Más accesible que los grandes de Ibiza. Si tienes agencia, es una buena puerta.', mejor: 'Temporada verano (jun-sep)' },
  { id: 126, name: 'Pikes Hotel Ibiza', city: 'Ibiza', country: 'España', area: 'San Antonio', type: 'club', genres: ['House', 'Disco', 'Eclectic'], score: 8.8, cachet: '€200–2000', aforo: '500', fundado: '1978', entrada_precio: '€20–40', entrada_tipo: 'high', entrada_nota: 'Hotel de culto con eventos nocturnos legendarios.', ambiente: 'Hotel boutique histórico con piscina y eventos nocturnos de culto.', reputacion: 'Los mejores por ambiente y trato a artistas. Muy especial.', artistas: 'Honey Dijon, Horse Meat Disco', contacto: 'info@pikesibiza.com', red_flag: '', consejo: 'Las noches de Freddie\'s (viernes) son históricas. Para house ecléctico y disco.', mejor: 'Viernes (Freddie\'s)', website: 'pikesibiza.com' },

  // ─────────────────────────────────────────────
  // VALENCIA
  // ─────────────────────────────────────────────
  { id: 74, name: 'Sala Matisse', city: 'Valencia', country: 'España', area: 'Ruzafa', type: 'club', genres: ['House', 'Techno', 'Electronic'], score: 8.0, cachet: '€60–280', aforo: '400', fundado: '2010', entrada_precio: '€8–15', entrada_tipo: 'low', entrada_nota: 'Club de referencia en Valencia. Programación cuidada.', ambiente: 'Club de referencia en Ruzafa. Escena electrónica seria y en crecimiento.', reputacion: 'Buenos pagadores para su tamaño. Abiertos a DJs europeos.', artistas: 'DJs de house y techno europeos y nacionales', contacto: 'booking@salamatisse.com', red_flag: '', consejo: 'Valencia tiene escena creciente. Buena puerta de entrada al circuito del Mediterráneo.', mejor: 'Viernes y sábado' },
  { id: 76, name: 'Radio City Valencia', city: 'Valencia', country: 'España', area: 'Barrio del Carmen', type: 'bar', genres: ['Flamenco', 'Electronic', 'Afro', 'World'], score: 7.9, cachet: '€30–120', aforo: '150', fundado: '1982', entrada_precio: '€5–8', entrada_tipo: 'low', entrada_nota: 'Bar histórico del Carmen. Programación muy ecléctica.', ambiente: 'Bar cultural histórico en el Carmen. Mezcla flamenco, electrónica y música del mundo.', reputacion: 'Institución local. Buenos con artistas eclécticos.', artistas: 'DJs de world music y electrónica alternativa', contacto: 'info@radiocityvalencia.es', red_flag: '', consejo: 'Si haces world music o electrónica con raíces culturales, encaja perfecto.', mejor: 'Jueves, viernes y sábado' },
  { id: 77, name: 'Spook Club Valencia', city: 'Valencia', country: 'España', area: 'Benimaclet', type: 'club', genres: ['Techno', 'House', 'Minimal'], score: 7.8, cachet: '€50–220', aforo: '300', fundado: '2012', entrada_precio: '€6–12', entrada_tipo: 'low', entrada_nota: 'Club en Benimaclet. Escena joven y underground.', ambiente: 'Club de barrio con escena joven y muy underground en Benimaclet.', reputacion: 'Buenos para artistas emergentes. Cachets bajos pero muy receptivos.', artistas: 'DJs locales y nacionales emergentes', contacto: 'info@spookclub.es', red_flag: '', consejo: 'Ideal para primeros bookings en Valencia. Ambiente muy abierto.', mejor: 'Sábado' },
  { id: 78, name: 'Akuarela Playa', city: 'Valencia', country: 'España', area: 'El Saler', type: 'festival', genres: ['Techno', 'House', 'Electronic'], score: 8.3, cachet: '€100–600', aforo: '3000', fundado: '2000', entrada_precio: '€10–20', entrada_tipo: 'mid', entrada_nota: 'Festival de playa en verano. Referencia en el Mediterráneo español.', ambiente: 'Festival open air en la playa del Saler. Referencia del verano valenciano.', reputacion: 'Buenos pagadores. Producción correcta para festivales de playa.', artistas: 'DJs nacionales e internacionales de house y techno', contacto: 'booking@akuarela.com', red_flag: '', consejo: 'Muy buena visibilidad para DJs del circuito nacional. Contacta con antelación.', mejor: 'Temporada verano (jun-sep)' },

  // ─────────────────────────────────────────────
  // SEVILLA
  // ─────────────────────────────────────────────
  { id: 79, name: 'Antique Theatro', city: 'Sevilla', country: 'España', area: 'Centro', type: 'club', genres: ['House', 'Commercial', 'Electronic'], score: 7.8, cachet: '€80–400', aforo: '1500', fundado: '2003', entrada_precio: '€10–20', entrada_tipo: 'mid', entrada_nota: 'Club grande en el centro histórico. El más importante de Sevilla.', ambiente: 'Club de referencia sevillano. Ambiente festivo y muy local.', reputacion: 'Buenos pagadores. Abiertos a DJs de house con nombre.', artistas: 'DJs nacionales e internacionales de house y commercial', contacto: 'booking@antiquetheatrosevillx.com', red_flag: '', consejo: 'Referencia en Sevilla. Contacta si tienes ya algún booking en el sur de España.', mejor: 'Viernes y sábado' },
  { id: 80, name: 'FunClub Sevilla', city: 'Sevilla', country: 'España', area: 'Triana', type: 'club', genres: ['Techno', 'House', 'Indie'], score: 7.5, cachet: '€40–180', aforo: '250', fundado: '2006', entrada_precio: '€6–10', entrada_tipo: 'low', entrada_nota: 'Sala en Triana. Programación ecléctica y muy local.', ambiente: 'Sala en Triana con buena programación de electrónica y indie.', reputacion: 'Buenos con artistas locales y nacionales.', artistas: 'DJs locales y nacionales emergentes', contacto: 'info@funclubsevilla.com', red_flag: '', consejo: 'Buena puerta de entrada a la escena de Sevilla.', mejor: 'Viernes y sábado' },

  // ─────────────────────────────────────────────
  // LONDRES
  // ─────────────────────────────────────────────
  { id: 25, name: 'Fabric', city: 'Londres', country: 'Reino Unido', area: 'Farringdon', type: 'club', genres: ['Techno', 'House', 'Drum & Bass'], score: 9.7, cachet: '€150–1000', aforo: '1500', fundado: '1999', entrada_precio: '£12–20', entrada_tipo: 'mid', entrada_nota: 'Precio estándar para Londres. Tres salas con géneros distintos.', ambiente: 'El club más importante de UK. Tres salas, sonido perfecto, sin compromiso.', reputacion: 'El mejor trato a artistas del mundo. Contratos impecables.', artistas: 'Craig Richards, Terry Francis, Skream', contacto: 'booking@fabriclondon.com', red_flag: '', consejo: 'La meta de cualquier DJ serio en UK. Necesitas reputación previa.', mejor: 'Viernes (Room Two) y sábado (Room One)', website: 'fabriclondon.com' },
  { id: 26, name: 'Printworks London', city: 'Londres', country: 'Reino Unido', area: 'Canada Water', type: 'club', genres: ['Techno', 'House', 'Electronic'], score: 9.1, cachet: '€200–1500', aforo: '2000', fundado: '2017', entrada_precio: '£15–25', entrada_tipo: 'mid', entrada_nota: 'Espacio único en antigua imprenta. Producción visual increíble.', ambiente: 'Espacio industrial único. Las mejores producciones visuales de Londres.', reputacion: 'Muy profesionales. Pagan bien. Producciones de primer nivel.', artistas: 'Helena Hauff, Peggy Gou, Aphex Twin', contacto: 'info@printworkslondon.com', red_flag: '', consejo: 'Busca eventos de promotores externos que alquilan el espacio.', mejor: 'Eventos especiales y temporada invierno' },
  { id: 27, name: 'Fold London', city: 'Londres', country: 'Reino Unido', area: 'Canning Town', type: 'club', genres: ['Techno', 'Experimental', 'Queer'], score: 8.6, cachet: '€80–400', aforo: '600', fundado: '2018', entrada_precio: '£10–18', entrada_tipo: 'mid', entrada_nota: 'Club queer-friendly. Muy respetado en la escena de Londres.', ambiente: 'Club underground queer en zona industrial. Muy community.', reputacion: 'Excelentes condiciones para artistas. Muy inclusivos y profesionales.', artistas: 'Objekt, Sherelle, Call Super', contacto: 'bookings@fold.london', red_flag: '', consejo: 'Ideal si tu música tiene componente queer o experimental.', mejor: 'Viernes y sábado' },
  { id: 28, name: 'Egg London', city: 'Londres', country: 'Reino Unido', area: 'Kings Cross', type: 'club', genres: ['House', 'Techno', 'Minimal'], score: 8.0, cachet: '€70–350', aforo: '800', fundado: '2003', entrada_precio: '£10–20', entrada_tipo: 'mid', entrada_nota: 'Abre 24h los fines de semana. Precio accesible para Londres.', ambiente: 'Club de 3 plantas con terrace en Kings Cross. Abierto 24h.', reputacion: 'Buenos pagadores. Abiertos a DJs internacionales.', artistas: 'Loco Dice, Francesca Lombardo, Archie Hamilton', contacto: 'booking@egglondon.net', red_flag: '', consejo: 'El formato 24h es ideal para DJs que quieren tocar en horario matinal.', mejor: 'Sábado noche – domingo tarde' },
  { id: 29, name: 'Corsica Studios', city: 'Londres', country: 'Reino Unido', area: 'Elephant & Castle', type: 'club', genres: ['Techno', 'Experimental', 'Electronic'], score: 8.4, cachet: '€50–300', aforo: '350', fundado: '2009', entrada_precio: '£8–15', entrada_tipo: 'low', entrada_nota: 'Precio accesible para Londres. Club underground con gran reputación.', ambiente: 'Club underground en dos salas. Escena muy artística y experimental.', reputacion: 'Muy respetados. Buenos con artistas emergentes con propuesta artística.', artistas: 'Actress, Batu, Nídia', contacto: 'bookings@corsicastudios.com', red_flag: '', consejo: 'Buena puerta de entrada en Londres si tienes propuesta artística sólida.', mejor: 'Viernes y sábado' },
  { id: 82, name: 'Oval Space', city: 'Londres', country: 'Reino Unido', area: 'Bethnal Green', type: 'club', genres: ['Techno', 'House', 'Electronic'], score: 8.5, cachet: '€80–400', aforo: '800', fundado: '2013', entrada_precio: '£10–18', entrada_tipo: 'mid', entrada_nota: 'Espacio industrial en Bethnal Green. Producción visual buena.', ambiente: 'Espacio industrial multiusos con terraza. Muy versátil y bien producido.', reputacion: 'Buenos pagadores. Muy profesionales. Escena creciente.', artistas: 'Helena Hauff, Skee Mask, Blawan', contacto: 'booking@ovalspace.co.uk', red_flag: '', consejo: 'Buena opción para DJs europeos en Londres. Propuesta artística valorada.', mejor: 'Viernes y sábado' },
  { id: 84, name: 'XOYO London', city: 'Londres', country: 'Reino Unido', area: 'Shoreditch', type: 'club', genres: ['House', 'Techno', 'Electronic'], score: 8.2, cachet: '€80–400', aforo: '700', fundado: '2010', entrada_precio: '£10–18', entrada_tipo: 'mid', entrada_nota: 'Club en Shoreditch. Residencias de verano muy conocidas.', ambiente: 'Club de referencia en Shoreditch. Residencias de 12 semanas muy seguidas.', reputacion: 'Muy profesionales. Buenos pagadores. Buena visibilidad.', artistas: 'Midland, Joy Orbison, Floating Points', contacto: 'booking@xoyo.co.uk', red_flag: '', consejo: 'Famoso por sus residencias de verano. Propón una residencia en lugar de un one-off.', mejor: 'Viernes y sábado', website: 'xoyo.co.uk' },
  { id: 88, name: 'Phonox', city: 'Londres', country: 'Reino Unido', area: 'Brixton', type: 'club', genres: ['House', 'Disco', 'Funk', 'Soul'], score: 8.3, cachet: '€60–300', aforo: '450', fundado: '2014', entrada_precio: '£8–15', entrada_tipo: 'low', entrada_nota: 'Club en Brixton. Residencias de DJs reconocidas.', ambiente: 'Club en Brixton con programación muy cuidada de house y soul.', reputacion: 'Muy respetados. Residencias largas con DJs de primer nivel.', artistas: 'Gilles Peterson, Floating Points, Joy Orbison', contacto: 'booking@phonox.co.uk', red_flag: '', consejo: 'Propón una residencia o colaboración con los promotores. Muy artístico.', mejor: 'Viernes y sábado', website: 'phonox.co.uk' },

  // ─────────────────────────────────────────────
  // AMSTERDAM
  // ─────────────────────────────────────────────
  { id: 31, name: 'Shelter Amsterdam', city: 'Amsterdam', country: 'Países Bajos', area: 'Overtoom', type: 'club', genres: ['Techno', 'House', 'Electronic'], score: 8.5, cachet: '€80–400', aforo: '500', fundado: '2015', entrada_precio: '€10–16', entrada_tipo: 'mid', entrada_nota: 'Club subterráneo bajo una piscina. Ambiente muy especial.', ambiente: 'Club bajo una piscina olímpica. Acústica increíble y ambiente único.', reputacion: 'Muy profesionales. Buenos pagadores para artistas con propuesta.', artistas: 'Identified Patient, Dj Stingray, Kode9', contacto: 'booking@shelteramsterdam.nl', red_flag: '', consejo: 'Envía propuesta artística sólida. Valoran la coherencia.', mejor: 'Viernes y sábado', website: 'shelteramsterdam.nl' },
  { id: 32, name: 'Paradiso Amsterdam', city: 'Amsterdam', country: 'Países Bajos', area: 'Leidseplein', type: 'club', genres: ['House', 'Electronic', 'Live'], score: 8.8, cachet: '€100–800', aforo: '1500', fundado: '1968', entrada_precio: '€12–25', entrada_tipo: 'mid', entrada_nota: 'Iglesia convertida en sala de conciertos y club. Icónica.', ambiente: 'Iglesia convertida. Icono cultural de Amsterdam. Muy variado.', reputacion: 'Institución. Excelentes condiciones para artistas.', artistas: 'Bicep, Jon Hopkins, Four Tet', contacto: 'booking@paradiso.nl', red_flag: '', consejo: 'Más orientado a actuaciones en directo. Bueno para DJ sets con componente live.', mejor: 'Eventos especiales y fines de semana', website: 'paradiso.nl' },
  { id: 90, name: 'Marktkantine', city: 'Amsterdam', country: 'Países Bajos', area: 'Oud-West', type: 'club', genres: ['House', 'Techno', 'Electronic'], score: 8.4, cachet: '€80–400', aforo: '700', fundado: '2016', entrada_precio: '€10–16', entrada_tipo: 'mid', entrada_nota: 'Club en antigua cantina de mercado. Programación muy cuidada.', ambiente: 'Antigua cantina de mercado convertida en club. Programación de calidad.', reputacion: 'Muy profesionales. Buenos pagadores para artistas europeos.', artistas: 'Antal, San Proper, Young Marco', contacto: 'booking@marktkantine.nl', red_flag: '', consejo: 'Uno de los clubs más respetados de Amsterdam. Propuesta artística primero.', mejor: 'Viernes y sábado' },
  { id: 91, name: 'Radion Amsterdam', city: 'Amsterdam', country: 'Países Bajos', area: 'Amsterdam-Zuidoost', type: 'club', genres: ['Techno', 'House', 'Experimental'], score: 8.7, cachet: '€80–450', aforo: '900', fundado: '2018', entrada_precio: '€10–18', entrada_tipo: 'mid', entrada_nota: 'Club nuevo con sistema de sonido de primer nivel.', ambiente: 'Club de referencia en Amsterdam. Sonido increíble y programación ambiciosa.', reputacion: 'Excelentes condiciones para artistas. Uno de los mejores de Holanda.', artistas: 'Identified Patient, Donato Dozzy, Surgeon', contacto: 'booking@radion.nl', red_flag: '', consejo: 'Si tienes propuesta techno o experimental seria, es el club más interesante de Amsterdam ahora.', mejor: 'Viernes y sábado', website: 'radion.nl' },
  { id: 92, name: 'Garage Noord', city: 'Amsterdam', country: 'Países Bajos', area: 'Amsterdam Noord', type: 'club', genres: ['House', 'Techno', 'Afro'], score: 7.9, cachet: '€50–250', aforo: '400', fundado: '2015', entrada_precio: '€8–14', entrada_tipo: 'low', entrada_nota: 'Club en Amsterdam Noord. Escena alternativa y ecléctica.', ambiente: 'Club en zona industrial de Noord. Muy ecléctico y comunitario.', reputacion: 'Buenos con artistas de géneros distintos. Ambiente muy abierto.', artistas: 'DJs de house, afro y techno', contacto: 'info@garagenoord.nl', red_flag: '', consejo: 'Noord tiene una escena creciente. Buena opción si ya tocas en Amsterdam.', mejor: 'Sábado' },

  // ─────────────────────────────────────────────
  // PARÍS
  // ─────────────────────────────────────────────
  { id: 34, name: 'Rex Club', city: 'París', country: 'Francia', area: 'Grands Boulevards', type: 'club', genres: ['Techno', 'House', 'Electronic'], score: 9.0, cachet: '€80–500', aforo: '500', fundado: '1990', entrada_precio: '€12–18', entrada_tipo: 'mid', entrada_nota: 'Institución del techno en París. Precio estándar francés.', ambiente: 'El club de techno más legendario de París. Sonido Laurent Garnier.', reputacion: 'Institución. Muy respetados. Buen trato a artistas.', artistas: 'Laurent Garnier, Miss Kittin, DJ Hell', contacto: 'booking@rexclub.com', red_flag: '', consejo: 'La referencia del techno en París. Envía mix técnico y con visión artística.', mejor: 'Viernes y sábado', website: 'rexclub.com' },
  { id: 35, name: 'Concrete Paris', city: 'París', country: 'Francia', area: 'Quai de la Rapée', type: 'club', genres: ['Techno', 'House', 'Experimental'], score: 8.8, cachet: '€80–450', aforo: '600', fundado: '2011', entrada_precio: '€12–20', entrada_tipo: 'mid', entrada_nota: 'Abre 24h. Barco en el Sena convertido en club.', ambiente: 'Club en barco en el Sena. Abierto 24h. Escena artística potente.', reputacion: 'Muy profesionales. Buenos con artistas europeos emergentes.', artistas: 'Dj Stingray, Paula Temple, Surgeon', contacto: 'booking@concreteparis.fr', red_flag: '', consejo: 'El Fabric de París. Necesitas reputación en la escena europea.', mejor: 'Viernes – sábado 24h', website: 'concreteparis.fr' },
  { id: 95, name: 'La Machine du Moulin Rouge', city: 'París', country: 'Francia', area: 'Pigalle', type: 'club', genres: ['Techno', 'House', 'Electronic'], score: 8.4, cachet: '€80–400', aforo: '800', fundado: '2009', entrada_precio: '€12–20', entrada_tipo: 'mid', entrada_nota: 'Club debajo del Moulin Rouge. Dos salas.', ambiente: 'Club en las entrañas del Moulin Rouge. Programación techno y house seria.', reputacion: 'Buenos pagadores. Muy profesionales. Escena parisina seria.', artistas: 'Dj Stingray, Paula Temple, Bambounou', contacto: 'booking@lamachineclub.com', red_flag: '', consejo: 'Una de las mejores opciones para DJs europeos en París.', mejor: 'Viernes y sábado', website: 'lamachinedumoulinrouge.com' },
  { id: 97, name: 'Djoon Paris', city: 'París', country: 'Francia', area: 'Bibliothèque', type: 'club', genres: ['Afro House', 'Soul', 'Deep House', 'Gospel House'], score: 8.6, cachet: '€60–300', aforo: '300', fundado: '2005', entrada_precio: '€10–18', entrada_tipo: 'mid', entrada_nota: 'Club especializado en afro house y soul. Referencia en Europa.', ambiente: 'El mejor club de afro house de París. Escena muy cálida y soulful.', reputacion: 'Muy respetados. Referencia mundial en afro house y gospel house.', artistas: 'Larry Heard, Louie Vega, Black Coffee', contacto: 'booking@djoon.fr', red_flag: '', consejo: 'Si haces afro house, deep house o gospel house, este es EL club en París.', mejor: 'Sábado', website: 'djoon.fr' },

  // ─────────────────────────────────────────────
  // LISBOA
  // ─────────────────────────────────────────────
  { id: 38, name: 'Lux Frágil', city: 'Lisboa', country: 'Portugal', area: 'Santa Apolónia', type: 'club', genres: ['House', 'Techno', 'Electronic'], score: 9.1, cachet: '€80–500', aforo: '800', fundado: '1998', entrada_precio: '€10–18', entrada_tipo: 'mid', entrada_nota: 'El mejor club de Lisboa. Precio justo para la calidad.', ambiente: 'El club más icónico de Portugal. Orillas del Tajo. Terrace con vistas.', reputacion: 'Institución. Pagan bien y trato excelente a artistas.', artistas: 'Laurent Garnier, Ricardo Villalobos, Joakim', contacto: 'booking@luxfragil.com', red_flag: '', consejo: 'La referencia en Lisboa. Envía propuesta artística seria con mix.', mejor: 'Jueves, viernes y sábado', website: 'luxfragil.com' },
  { id: 39, name: 'Village Underground Lisboa', city: 'Lisboa', country: 'Portugal', area: 'Alcântara', type: 'club', genres: ['Electronic', 'House', 'Indie'], score: 8.0, cachet: '€60–300', aforo: '500', fundado: '2014', entrada_precio: '€8–15', entrada_tipo: 'low', entrada_nota: 'Espacio cultural en vagones de tren. Ambiente muy creativo.', ambiente: 'Vagones de tren convertidos en club y espacio cultural. Único.', reputacion: 'Buenos con artistas creativos. Ambiente muy artístico.', artistas: 'DJs europeos de house y electronic', contacto: 'booking@vulisboa.com', red_flag: '', consejo: 'Perfecto para artistas con propuesta visual y artística.', mejor: 'Viernes y sábado' },
  { id: 40, name: 'Music Box Lisboa', city: 'Lisboa', country: 'Portugal', area: 'Cais do Sodré', type: 'club', genres: ['Indie', 'Electronic', 'House'], score: 7.7, cachet: '€50–250', aforo: '400', fundado: '2006', entrada_precio: '€7–12', entrada_tipo: 'low', entrada_nota: 'Precio muy accesible. Zona de Cais do Sodré muy activa.', ambiente: 'Club popular en zona de bares. Mezcla indie, electrónica y live.', reputacion: 'Buenos con nuevos artistas. Ambiente muy abierto.', artistas: 'DJs locales y europeos emergentes', contacto: 'info@musicbox-lisboa.com', red_flag: '', consejo: 'Buena puerta de entrada en Lisboa. Ambiente muy receptivo con nuevos DJs.', mejor: 'Viernes y sábado' },
  { id: 41, name: 'Ministerium Club', city: 'Lisboa', country: 'Portugal', area: 'Baixa', type: 'club', genres: ['Techno', 'House', 'Minimal'], score: 7.9, cachet: '€50–280', aforo: '350', fundado: '2018', entrada_precio: '€8–15', entrada_tipo: 'low', entrada_nota: 'Club subterráneo en el centro histórico.', ambiente: 'Club subterráneo con estética industrial. Escena techno seria.', reputacion: 'Buenos pagadores para su tamaño. Abiertos a DJs europeos.', artistas: 'DJs de techno y minimal europeos', contacto: 'booking@ministeriumclub.com', red_flag: '', consejo: 'Si haces techno minimal o industrial, encaja perfectamente aquí.', mejor: 'Viernes y sábado' },

  // ─────────────────────────────────────────────
  // MILÁN
  // ─────────────────────────────────────────────
  { id: 42, name: 'Volt Club', city: 'Milán', country: 'Italia', area: 'Navigli', type: 'club', genres: ['Techno', 'House', 'Electronic'], score: 8.3, cachet: '€80–400', aforo: '600', fundado: '2015', entrada_precio: '€10–18', entrada_tipo: 'mid', entrada_nota: 'Club moderno en zona Navigli. Precio estándar milanés.', ambiente: 'Club de diseño en zona Navigli. Estética muy italiana y refinada.', reputacion: 'Buenos pagadores. Muy profesionales en la organización.', artistas: 'DJs de techno y house europeos', contacto: 'booking@voltmilano.com', red_flag: '', consejo: 'La escena de Milán es muy fashion. Cuida también tu imagen artística.', mejor: 'Viernes y sábado' },
  { id: 43, name: 'Plastic Milano', city: 'Milán', country: 'Italia', area: 'Porta Venezia', type: 'club', genres: ['House', 'Disco', 'Queer'], score: 8.5, cachet: '€70–350', aforo: '400', fundado: '1980', entrada_precio: '€10–20', entrada_tipo: 'mid', entrada_nota: 'Histórico club queer de Milán. Ambiente muy fashion.', ambiente: 'Club histórico queer. Icono de la noche y la moda en Milán.', reputacion: 'Institución. Pagan bien. Ambiente muy fashion y artístico.', artistas: 'DJs de house y disco internacionales', contacto: 'info@plastico.it', red_flag: '', consejo: 'Perfecto si haces house o disco con estética fashion o queer.', mejor: 'Viernes y sábado', website: 'plastico.it' },
  { id: 44, name: 'Tunnel Milano', city: 'Milán', country: 'Italia', area: 'Porta Garibaldi', type: 'club', genres: ['Techno', 'Industrial', 'EBM'], score: 8.1, cachet: '€60–300', aforo: '500', fundado: '2003', entrada_precio: '€8–15', entrada_tipo: 'low', entrada_nota: 'Club en túnel subterráneo. Escena techno muy dura.', ambiente: 'Literalmente un túnel subterráneo. Techno oscuro e industrial.', reputacion: 'Buenos con artistas de techno duro. Ambiente muy auténtico.', artistas: 'Ancient Methods, Phase, Rebekah', contacto: 'info@tunnelmilano.com', red_flag: '', consejo: 'Solo si haces techno industrial o muy oscuro. No apto para house.', mejor: 'Sábado' },
  { id: 103, name: 'Rocket Club Milano', city: 'Milán', country: 'Italia', area: 'Navigli', type: 'club', genres: ['House', 'Disco', 'Afro'], score: 8.0, cachet: '€60–280', aforo: '350', fundado: '2010', entrada_precio: '€8–15', entrada_tipo: 'low', entrada_nota: 'Club en Navigli. Ambiente muy festivo y cosmopolita.', ambiente: 'Club en la zona Navigli. House, disco y afro en un ambiente muy positivo.', reputacion: 'Buenos con artistas de house y afro. Ambiente muy festivo.', artistas: 'DJs de afro house y disco internacionales', contacto: 'info@rocketmilano.it', red_flag: '', consejo: 'Perfecto si haces afro house, disco o house festivo.', mejor: 'Viernes y sábado' },

  // ─────────────────────────────────────────────
  // HAMBURGO
  // ─────────────────────────────────────────────
  { id: 106, name: 'Docks Hamburg', city: 'Hamburgo', country: 'Alemania', area: 'St. Pauli', type: 'club', genres: ['Techno', 'House', 'Electronic'], score: 8.3, cachet: '€80–400', aforo: '1500', fundado: '1990', entrada_precio: '€10–18', entrada_tipo: 'mid', entrada_nota: 'Club de referencia en la Reeperbahn. Histórico.', ambiente: 'Sala de referencia en St. Pauli. La segunda ciudad del clubbing alemán.', reputacion: 'Buenos pagadores. Muy profesionales. Escena estable y seria.', artistas: 'DJs de techno y house europeos', contacto: 'booking@docks-hamburg.de', red_flag: '', consejo: 'Hamburgo es escena seria. Buen mercado para DJs que ya tienen reputación en Alemania.', mejor: 'Viernes y sábado' },
  { id: 107, name: 'Uebel & Gefährlich', city: 'Hamburgo', country: 'Alemania', area: 'Feldstraße', type: 'club', genres: ['Techno', 'House', 'Experimental'], score: 8.5, cachet: '€60–300', aforo: '600', fundado: '2007', entrada_precio: '€8–15', entrada_tipo: 'low', entrada_nota: 'Club en antiguo búnker antiaéreo. Ambiente increíble.', ambiente: 'Club en búnker antiaéreo de la WWII. Tres pisos, atmosphere increíble.', reputacion: 'Muy respetados. Excelentes condiciones para artistas.', artistas: 'Surgeon, Blawan, Skee Mask', contacto: 'booking@uebelundgefaehrlich.com', red_flag: '', consejo: 'Una de las mejores acústicas de Alemania. Si haces techno, priorízalo.', mejor: 'Viernes y sábado', website: 'uebelundgefaehrlich.com' },
  { id: 109, name: 'Golden Pudel Club', city: 'Hamburgo', country: 'Alemania', area: 'St. Pauli', type: 'bar', genres: ['Techno', 'Experimental', 'Electronic', 'Punk'], score: 8.2, cachet: '€30–150', aforo: '150', fundado: '1994', entrada_precio: '€5–8', entrada_tipo: 'low', entrada_nota: 'Bar-club legendario en St. Pauli. Programación muy curada.', ambiente: 'Bar-club de culto en St. Pauli. Escena muy influyente y cuidada.', reputacion: 'Institución underground. Cachets bajos pero impacto artístico enorme.', artistas: 'Lena Willikens, Palms Trax, Vladimir Ivkovic', contacto: 'info@pudel.com', red_flag: '', consejo: 'Un Pudel Club en el CV es como una medalla. Intenta conseguirlo.', mejor: 'Cualquier día de la semana' },

  // ─────────────────────────────────────────────
  // PRAGA
  // ─────────────────────────────────────────────
  { id: 111, name: 'Ankali Prague', city: 'Praga', country: 'República Checa', area: 'Žižkov', type: 'club', genres: ['Techno', 'House', 'Experimental'], score: 8.7, cachet: '€60–300', aforo: '500', fundado: '2016', entrada_precio: '€6–12', entrada_tipo: 'low', entrada_nota: 'El mejor club de Praga. Programación de primer nivel europeo.', ambiente: 'El club de referencia de Praga. Escena muy seria y artística.', reputacion: 'Excelentes condiciones para artistas. Muy respetados en Europa del Este.', artistas: 'Surgeon, Paula Temple, Objekt', contacto: 'booking@ankali.cz', red_flag: '', consejo: 'El Berghain de Praga. Si tienes propuesta seria, un booking aquí es muy valioso.', mejor: 'Viernes y sábado', website: 'ankali.cz' },
  { id: 113, name: 'Cross Club Prague', city: 'Praga', country: 'República Checa', area: 'Holešovice', type: 'club', genres: ['Techno', 'Industrial', 'Cyberpunk', 'Experimental'], score: 8.0, cachet: '€30–150', aforo: '400', fundado: '2005', entrada_precio: '€4–8', entrada_tipo: 'low', entrada_nota: 'Club cyberpunk único en Europa. Decoración industrial insana.', ambiente: 'Club cyberpunk con decoración industrial única. Muy especial y alternativo.', reputacion: 'Buenos para artistas industriales y experimentales. Ambiente único.', artistas: 'DJs de techno industrial y experimental', contacto: 'info@crossclub.cz', red_flag: '', consejo: 'Único en Europa por su estética. Si tu música encaja con lo industrial, imprescindible.', mejor: 'Viernes y sábado' },

  // ─────────────────────────────────────────────
  // VARSOVIA
  // ─────────────────────────────────────────────
  { id: 115, name: 'Smolna Warsaw', city: 'Varsovia', country: 'Polonia', area: 'Śródmieście', type: 'club', genres: ['Techno', 'House', 'Experimental'], score: 8.8, cachet: '€60–300', aforo: '600', fundado: '2014', entrada_precio: '€8–14', entrada_tipo: 'low', entrada_nota: 'El club de referencia de Varsovia. Programación internacional.', ambiente: 'El club más respetado de Polonia. Programación muy cuidada e internacional.', reputacion: 'Excelentes condiciones para artistas. Los mejores de Polonia.', artistas: 'Surgeon, Dj Stingray, Paula Temple', contacto: 'booking@smolna.com', red_flag: '', consejo: 'El Ankali de Polonia. Booking aquí tiene mucho valor para el CV europeo.', mejor: 'Viernes y sábado', website: 'smolna.com' },
  { id: 116, name: 'Jasna 1', city: 'Varsovia', country: 'Polonia', area: 'Śródmieście', type: 'club', genres: ['Techno', 'House', 'Electronic'], score: 8.2, cachet: '€50–250', aforo: '500', fundado: '2010', entrada_precio: '€6–12', entrada_tipo: 'low', entrada_nota: 'Club histórico de Varsovia. Escena techno muy consolidada.', ambiente: 'Club veterano de la escena techno de Varsovia. Muy respetado.', reputacion: 'Buenos pagadores. Abiertos a DJs europeos con propuesta.', artistas: 'DJs de techno y house europeos', contacto: 'booking@jasna1.pl', red_flag: '', consejo: 'Polonia tiene escena muy activa. Jasna 1 es buena puerta de entrada.', mejor: 'Viernes y sábado' },

  // ─────────────────────────────────────────────
  // BRUSELAS
  // ─────────────────────────────────────────────
  { id: 118, name: 'Fuse Club Brussels', city: 'Bruselas', country: 'Bélgica', area: 'Ixelles', type: 'club', genres: ['Techno', 'House', 'Electronic'], score: 8.9, cachet: '€80–400', aforo: '700', fundado: '1994', entrada_precio: '€10–18', entrada_tipo: 'mid', entrada_nota: 'El club de referencia de Bélgica. 30 años de historia.', ambiente: 'Institución belga. El club más respetado del país con 30 años de historia.', reputacion: 'Institución. Excelentes condiciones para artistas. Muy respetados.', artistas: 'Laurent Garnier, Jeff Mills, Ken Ishii', contacto: 'booking@fuse.be', red_flag: '', consejo: 'La referencia absoluta de Bélgica. Un booking aquí es muy valioso.', mejor: 'Sábado', website: 'fuse.be' },
  { id: 120, name: 'C12 Brussels', city: 'Bruselas', country: 'Bélgica', area: 'Centre', type: 'club', genres: ['Techno', 'House', 'Minimal'], score: 8.4, cachet: '€60–280', aforo: '450', fundado: '2012', entrada_precio: '€8–16', entrada_tipo: 'mid', entrada_nota: 'Club moderno en el centro. Programación muy cuidada.', ambiente: 'Club moderno con programación seria de techno y house en el centro.', reputacion: 'Muy profesionales. Buenos con artistas europeos.', artistas: 'DVS1, Objekt, Call Super', contacto: 'booking@c12.be', red_flag: '', consejo: 'Segunda mejor opción en Bruselas tras Fuse. Muy serios y profesionales.', mejor: 'Viernes y sábado', website: 'c12.be' },

  // ─────────────────────────────────────────────
  // ZÚRICH
  // ─────────────────────────────────────────────
  { id: 121, name: 'Hive Club Zurich', city: 'Zúrich', country: 'Suiza', area: 'Langstrasse', type: 'club', genres: ['Techno', 'House', 'Electronic'], score: 8.6, cachet: '€100–500', aforo: '500', fundado: '2006', entrada_precio: 'CHF 15–25', entrada_tipo: 'mid', entrada_nota: 'El mejor club de Zúrich. Programación de primer nivel europeo.', ambiente: 'El club de referencia en Zúrich. Escena muy seria y con presupuesto.', reputacion: 'Excelentes pagadores (Suiza = cachets más altos). Muy profesionales.', artistas: 'Surgeon, Paula Temple, DVS1', contacto: 'booking@hiveclub.ch', red_flag: '', consejo: 'Suiza paga muy bien. Un booking en Hive vale económicamente mucho más que otros países.', mejor: 'Viernes y sábado', website: 'hiveclub.ch' },
  { id: 122, name: 'Zukunft Club', city: 'Zúrich', country: 'Suiza', area: 'Langstrasse', type: 'club', genres: ['House', 'Disco', 'Funk', 'Experimental'], score: 8.3, cachet: '€80–350', aforo: '300', fundado: '2010', entrada_precio: 'CHF 10–20', entrada_tipo: 'mid', entrada_nota: 'Club de house y disco muy respetado en Zúrich.', ambiente: 'Club de house y disco íntimo. Escena muy artística y de culto.', reputacion: 'Muy respetados. Buenos pagadores. Escena muy curada.', artistas: 'Gerd Janson, Young Marco, San Proper', contacto: 'booking@zukunft.org', red_flag: '', consejo: 'Si haces house o disco, Zukunft es el club más adecuado en Zúrich.', mejor: 'Viernes y sábado', website: 'zukunft.org' },

  // ─────────────────────────────────────────────
  // FESTIVALES
  // ─────────────────────────────────────────────
  { id: 46, name: 'Sonar Festival', city: 'Barcelona', country: 'España', area: 'Fira Barcelona', type: 'festival', genres: ['Electronic', 'Techno', 'Experimental', 'Live'], score: 9.5, cachet: '€200–5000', aforo: '120000', fundado: '1994', entrada_precio: '€50–200', entrada_tipo: 'high', entrada_nota: 'Festival de 3 días. Day y Night pass por separado.', ambiente: 'El festival de música electrónica más importante del mundo hispano.', reputacion: 'Institución mundial. Pagan muy bien. Producciones de primer nivel.', artistas: 'Aphex Twin, Bicep, Four Tet, Björk', contacto: 'booking@sonar.es', red_flag: '', consejo: 'Necesitas agencia internacional consolidada. Target a largo plazo.', mejor: 'Junio', website: 'sonar.es' },
  { id: 47, name: 'Dekmantel Festival', city: 'Amsterdam', country: 'Países Bajos', area: 'Amsterdamse Bos', type: 'festival', genres: ['House', 'Techno', 'Experimental'], score: 9.4, cachet: '€200–3000', aforo: '15000', fundado: '2012', entrada_precio: '€40–120', entrada_tipo: 'high', entrada_nota: 'Festival de 3 días en el bosque. Entradas se agotan en minutos.', ambiente: 'El festival de culto del house y techno europeo. En el bosque de Amsterdam.', reputacion: 'Los mejores de Europa en cuidar la programación artística.', artistas: 'Hunee, Antal, Call Super, Objekt', contacto: 'booking@dekmantelfestival.com', red_flag: '', consejo: 'Muy selectivo. Prioriza DJs con propuesta artística única.', mejor: 'Agosto', website: 'dekmantelfestival.com' },
  { id: 48, name: 'Boiler Room', city: 'Múltiples ciudades', country: 'Europa', area: 'Varios', type: 'festival', genres: ['House', 'Techno', 'Grime', 'Experimental'], score: 9.2, cachet: '€100–2000', aforo: '500', fundado: '2010', entrada_precio: 'Gratis (lista)', entrada_tipo: 'free', entrada_nota: 'Invitación por lista. Contenido transmitido online a millones.', ambiente: 'Eventos de streaming en vivo. Enorme visibilidad online global.', reputacion: 'Excelente para visibilidad. Pagan correcto. Muy profesionales.', artistas: 'Todos los grandes de la escena electrónica mundial', contacto: 'booking@boilerroom.tv', red_flag: '', consejo: 'Un Boiler Room puede cambiar tu carrera. Necesitas recomendación de alguien dentro.', mejor: 'Todo el año en distintas ciudades', website: 'boilerroom.tv' },
  { id: 127, name: 'ADE (Amsterdam Dance Event)', city: 'Amsterdam', country: 'Países Bajos', area: 'Ciudad entera', type: 'festival', genres: ['House', 'Techno', 'Electronic', 'Experimental'], score: 9.8, cachet: '€50–5000', aforo: '400000', fundado: '1996', entrada_precio: '€15–60', entrada_tipo: 'high', entrada_nota: 'El mayor festival de música electrónica del mundo (5 días).', ambiente: 'La semana de música electrónica más importante del mundo. Toda Amsterdam es un club.', reputacion: 'Estándar absoluto de la industria. Todo el mundo está ahí.', artistas: 'Todo el mundo', contacto: 'info@amsterdam-dance-event.nl', red_flag: '', consejo: 'ADE es también conferencia. Compra badge de industria. Esencial para networking.', mejor: 'Octubre (5 días)', website: 'amsterdam-dance-event.nl' },
  { id: 128, name: 'Awakenings Festival', city: 'Amsterdam', country: 'Países Bajos', area: 'Spaarnwoude', type: 'festival', genres: ['Techno', 'Industrial Techno', 'Electronic'], score: 9.3, cachet: '€200–3000', aforo: '25000', fundado: '1997', entrada_precio: '€35–80', entrada_tipo: 'high', entrada_nota: 'El festival de techno más importante de Holanda.', ambiente: 'El festival de techno más serio de Holanda. Producción de primer nivel.', reputacion: 'Muy profesionales. Buenos pagadores. Referencia del techno europeo.', artistas: 'Richie Hawtin, Ben Klock, Adam Beyer', contacto: 'booking@awakenings.com', red_flag: '', consejo: 'Necesitas nombre en la escena techno europea. Target a medio-largo plazo.', mejor: 'Junio', website: 'awakenings.com' },
  { id: 130, name: 'Primavera Sound', city: 'Barcelona', country: 'España', area: 'Parc del Fòrum', type: 'festival', genres: ['Indie', 'Electronic', 'Experimental', 'Pop'], score: 9.4, cachet: '€200–5000', aforo: '200000', fundado: '2001', entrada_precio: '€65–250', entrada_tipo: 'high', entrada_nota: 'Uno de los mejores festivales de música del mundo.', ambiente: 'Uno de los festivales más respetados del mundo. Muy ecléctico y artístico.', reputacion: 'Institución. Pagan muy bien. Escena artística de primer nivel.', artistas: 'Massive Attack, FKA twigs, LCD Soundsystem', contacto: 'booking@primaverasound.com', red_flag: '', consejo: 'Necesitas agencia con presencia internacional. Target a largo plazo.', mejor: 'Junio', website: 'primaverasound.com' },
  { id: 133, name: 'Junction 2 Festival', city: 'Londres', country: 'Reino Unido', area: 'Boston Manor Park', type: 'festival', genres: ['Techno', 'House', 'Electronic'], score: 8.9, cachet: '€150–2000', aforo: '10000', fundado: '2016', entrada_precio: '£45–80', entrada_tipo: 'high', entrada_nota: 'El mejor festival de techno de UK.', ambiente: 'El festival de techno más respetado del Reino Unido. Muy curado.', reputacion: 'Los mejores en cuidar la programación artística en UK. Muy profesionales.', artistas: 'Ben Klock, Surgeon, Paula Temple', contacto: 'info@junction2.co.uk', red_flag: '', consejo: 'Si haces techno serio en UK, Junction 2 es el objetivo. Necesitas propuesta artística clara.', mejor: 'Junio', website: 'junction2.co.uk' },
]

// Utilidades
export const CITIES = Array.from(new Set(VENUES_DB.map(v => v.city))).sort()
export const COUNTRIES = Array.from(new Set(VENUES_DB.map(v => v.country))).sort()

export function getVenuesByCity(city: string): VenueDB[] {
  return VENUES_DB.filter(v => v.city === city)
}

export function getVenuesByType(type: VenueDB['type']): VenueDB[] {
  return VENUES_DB.filter(v => v.type === type)
}

export function searchVenues(query: string): VenueDB[] {
  const q = query.toLowerCase()
  return VENUES_DB.filter(v =>
    v.name.toLowerCase().includes(q) ||
    v.city.toLowerCase().includes(q) ||
    v.genres.some(g => g.toLowerCase().includes(q)) ||
    v.area.toLowerCase().includes(q)
  )
}

export const VENUE_STATS = {
  total: VENUES_DB.length,
  clubs: VENUES_DB.filter(v => v.type === 'club').length,
  bars: VENUES_DB.filter(v => v.type === 'bar').length,
  festivals: VENUES_DB.filter(v => v.type === 'festival').length,
  cities: CITIES.length,
}

export function getVenueCountByCity(): Record<string, number> {
  return VENUES_DB.reduce((acc, v) => {
    acc[v.city] = (acc[v.city] || 0) + 1
    return acc
  }, {} as Record<string, number>)
}
