// ================================================
// DJBOOK PRO — Base de datos de venues europeos
// ~100 venues en 9 ciudades
// ================================================

export interface VenueDB {
  id: number
  name: string
  city: string
  country: string
  area: string
  type: 'club' | 'bar' | 'festival'
  genres: string[]
  score: number
  cachet: string
  aforo: string
  fundado: string
  entrada_precio: string
  entrada_tipo: 'free' | 'low' | 'mid' | 'high'
  entrada_nota: string
  ambiente: string
  reputacion: string
  artistas: string
  contacto: string
  red_flag: string
  consejo: string
  mejor: string
  website?: string
  instagram?: string
}

export const VENUES_DB: VenueDB[] = [

  // ─────────────────────────────────────────────
  // BERLÍN
  // ─────────────────────────────────────────────
  { id: 1, name: 'Berghain', city: 'Berlín', country: 'Alemania', area: 'Friedrichshain', type: 'club', genres: ['Techno', 'Industrial'], score: 9.8, cachet: '€150–800', aforo: '1500', fundado: '2004', entrada_precio: '€15–20', entrada_tipo: 'high', entrada_nota: 'Precio variable. La cola puede durar horas. Sin garantía de entrada.', ambiente: 'La catedral del techno mundial. Ambiente oscuro, dress code estricto, sets de 6-8h.', reputacion: 'Pagan bien y a tiempo. Contratos claros. El estándar de la industria.', artistas: 'Ben Klock, Len Faki, Marcel Dettmann', contacto: 'Solo por recomendación directa o representante.', red_flag: '', consejo: 'No contactes directamente. Necesitas un agente o que un residente te recomiende.', mejor: 'Viernes noche – domingo tarde', instagram: '@berghain_berlin' },
  { id: 2, name: 'Tresor', city: 'Berlín', country: 'Alemania', area: 'Mitte', type: 'club', genres: ['Techno', 'Detroit Techno'], score: 9.2, cachet: '€100–600', aforo: '800', fundado: '1991', entrada_precio: '€12–18', entrada_tipo: 'mid', entrada_nota: 'Precio estándar para Berlín. Sin dress code estricto.', ambiente: 'Club histórico en bunker subterráneo. El techno más duro de Berlín.', reputacion: 'Institución. Pagan correctamente. Valoran la autenticidad artística.', artistas: 'DVS1, Surgeon, Planetary Assault Systems', contacto: 'booking@tresorberlin.com — presenta tu SoundCloud y mix.', red_flag: '', consejo: 'Envía un mix de mínimo 1h en la línea Tresor. Sin concesiones comerciales.', mejor: 'Viernes y sábado madrugada', website: 'tresorberlin.com' },
  { id: 3, name: 'Watergate', city: 'Berlín', country: 'Alemania', area: 'Kreuzberg', type: 'club', genres: ['House', 'Techno', 'Deep House'], score: 8.9, cachet: '€80–500', aforo: '600', fundado: '2002', entrada_precio: '€10–15', entrada_tipo: 'mid', entrada_nota: 'Más accesible que otros clubs top de Berlín.', ambiente: 'Club con terraza al río Spree. Equilibrio perfecto entre house y techno.', reputacion: 'Buenos pagadores. Abiertos a nuevos DJs con buen material.', artistas: 'Maceo Plex, Dixon, Âme', contacto: 'booking@water-gate.de — incluye bio, mix y links.', red_flag: '', consejo: 'Tu estilo debe encajar entre house y techno. Revisa su lineup reciente.', mejor: 'Fin de semana, terraza en verano', website: 'water-gate.de' },
  { id: 4, name: 'Sisyphos', city: 'Berlín', country: 'Alemania', area: 'Lichtenberg', type: 'club', genres: ['House', 'Techno', 'Mixed'], score: 8.7, cachet: '€60–350', aforo: '3000', fundado: '2013', entrada_precio: '€8–12', entrada_tipo: 'low', entrada_nota: 'Precio bajo para el tamaño. Fiestas de 72h el fin de semana.', ambiente: 'Antiguo complejo industrial. Fiesta de 72h los fines de semana. Muy community.', reputacion: 'Pagan correcto. Gran oportunidad para DJs emergentes en stages secundarios.', artistas: 'Marquis Hawkes, Lena Willikens', contacto: 'booking@sisyphos-berlin.de', red_flag: 'El stage principal es difícil. Empieza por los stages pequeños.', consejo: 'Ideal para DJs nuevos. Propón comenzar en el stage Hof o Pferdestall.', mejor: 'Domingo tarde (marathon sets)' },
  { id: 5, name: 'About Blank', city: 'Berlín', country: 'Alemania', area: 'Friedrichshain', type: 'club', genres: ['Techno', 'Experimental', 'Queer'], score: 8.5, cachet: '€50–300', aforo: '400', fundado: '2010', entrada_precio: '€8–14', entrada_tipo: 'low', entrada_nota: 'Accesible. Algunas noches queer tienen precio reducido.', ambiente: 'Club alternativo y queer-friendly. Jardín enorme. Ambiente muy community.', reputacion: 'Excelente trato a artistas. Muy inclusivos. Pagan bien para su tamaño.', artistas: 'Objekt, Hunee, Special Request', contacto: 'booking@aboutblank.li', red_flag: '', consejo: 'Prioriza si tu música tiene dimensión política o queer.', mejor: 'Viernes queer, sábado techno' },
  { id: 6, name: 'Ohm', city: 'Berlín', country: 'Alemania', area: 'Mitte', type: 'club', genres: ['Techno', 'Experimental'], score: 8.6, cachet: '€80–400', aforo: '300', fundado: '2016', entrada_precio: '€12–16', entrada_tipo: 'mid', entrada_nota: 'En Kraftwerk Berlin. Precio justo para la calidad acústica.', ambiente: 'Club en Kraftwerk Berlin. Acústica perfecta. Muy artístico y serio.', reputacion: 'Excelentes condiciones para artistas. Muy profesionales.', artistas: 'Shackleton, Actress, Burial', contacto: 'booking@ohm-berlin.com', red_flag: '', consejo: 'Si haces techno experimental o club music seria, es tu sitio.', mejor: 'Viernes' },
  { id: 7, name: 'Monarch Bar', city: 'Berlín', country: 'Alemania', area: 'Kreuzberg', type: 'bar', genres: ['House', 'Indie', 'Mixed'], score: 7.5, cachet: '€30–120', aforo: '150', fundado: '2005', entrada_precio: 'Gratis', entrada_tipo: 'free', entrada_nota: 'Sin entrada. Consumición mínima algunos días.', ambiente: 'Bar con cabina encima de un supermercado turco. Atmosférico y peculiar.', reputacion: 'Pagan poco pero es buen lugar para empezar. Muy chill.', artistas: 'DJs locales emergentes', contacto: 'info@monarchbar.de o directo en persona', red_flag: '', consejo: 'Ideal para primer booking pagado en Berlín.', mejor: 'Jueves y viernes' },
  { id: 8, name: 'Ritter Butzke', city: 'Berlín', country: 'Alemania', area: 'Kreuzberg', type: 'club', genres: ['House', 'Techno', 'Soul'], score: 8.1, cachet: '€60–300', aforo: '700', fundado: '2007', entrada_precio: '€8–12', entrada_tipo: 'low', entrada_nota: 'Precio accesible. Buena relación calidad-precio.', ambiente: 'Club en fábrica con varios pisos. Equilibrio entre techno y house.', reputacion: 'Buenos pagadores. Abiertos a DJs internacionales nuevos.', artistas: 'Âme, Chaim, Tama Sumo', contacto: 'booking@ritterbutzke.de — incluye SoundCloud y bio.', red_flag: '', consejo: 'Buen punto de entrada al circuito serio de Berlín.', mejor: 'Sábado' },
  { id: 9, name: 'Panorama Bar', city: 'Berlín', country: 'Alemania', area: 'Friedrichshain', type: 'club', genres: ['House', 'Electro'], score: 9.5, cachet: '€120–700', aforo: '800', fundado: '2004', entrada_precio: '€15–20', entrada_tipo: 'high', entrada_nota: 'Mismo edificio que Berghain, planta superior. Entrada conjunta.', ambiente: 'Planta superior del Berghain. House y electro. Luz natural por las mañanas.', reputacion: 'Igual que Berghain: profesionales y bien pagadores.', artistas: 'Honey Dijon, Peggy Gou, Prosumer', contacto: 'Mismo proceso que Berghain. Solo por agente.', red_flag: '', consejo: 'Si haces house, este es tu objetivo en Berghain. Mismo proceso de booking.', mejor: 'Sábado madrugada – domingo mañana' },

  // ─────────────────────────────────────────────
  // MADRID
  // ─────────────────────────────────────────────
  { id: 10, name: 'Fabrik', city: 'Madrid', country: 'España', area: 'Fuenlabrada', type: 'club', genres: ['Techno', 'Trance', 'Hard Dance'], score: 8.8, cachet: '€200–1500', aforo: '5000', fundado: '2002', entrada_precio: '€12–20', entrada_tipo: 'mid', entrada_nota: 'Precio variable según artista. Abonos de temporada disponibles.', ambiente: 'El club más grande de España. Sonido brutal. Shows de producción visual.', reputacion: 'Buenos pagadores. Muy profesionales. Producción de primer nivel.', artistas: 'Richie Hawtin, Carl Cox, Amelie Lens', contacto: 'booking@fabricmadrid.com', red_flag: '', consejo: 'Difícil para DJs nuevos en el escenario principal. Busca eventos secundarios.', mejor: 'Sábado noche', website: 'fabricmadrid.com' },
  { id: 11, name: 'Sala Charada', city: 'Madrid', country: 'España', area: 'Centro', type: 'club', genres: ['House', 'Techno', 'Minimal'], score: 7.8, cachet: '€80–350', aforo: '400', fundado: '2015', entrada_precio: '€8–15', entrada_tipo: 'low', entrada_nota: 'Precio accesible. Listas hasta las 2am gratuitas.', ambiente: 'Sala mediana en el centro. Sonido bueno, ambiente sin pretensiones.', reputacion: 'Pagan correctamente. Buenos con DJs nuevos con potencial.', artistas: 'DJs locales y europeos emergentes', contacto: 'booking@salacharda.com', red_flag: '', consejo: 'Buena puerta de entrada a la escena de Madrid. Manda mix + bio.', mejor: 'Viernes y sábado' },
  { id: 12, name: 'Teatro Kapital', city: 'Madrid', country: 'España', area: 'Atocha', type: 'club', genres: ['Commercial', 'House', 'Hip-Hop'], score: 6.5, cachet: '€100–500', aforo: '2000', fundado: '1994', entrada_precio: '€15–25', entrada_tipo: 'high', entrada_nota: '7 plantas temáticas. Precio incluye consumición.', ambiente: 'Mega club comercial en edificio teatral histórico. 7 pisos de música.', reputacion: 'Pagan bien pero el ambiente es muy comercial.', artistas: 'DJs comerciales y celebrities', contacto: 'booking@grupo-kapital.com', red_flag: 'Muy comercial. No recomendable para DJs de electrónica seria.', consejo: 'Solo si haces música comercial o eres DJ residente de eventos privados.', mejor: 'Jueves, viernes y sábado' },
  { id: 13, name: 'Mondo Disko', city: 'Madrid', country: 'España', area: 'Malasaña', type: 'club', genres: ['Disco', 'House', 'Funk'], score: 8.0, cachet: '€60–250', aforo: '300', fundado: '2010', entrada_precio: '€6–10', entrada_tipo: 'low', entrada_nota: 'Muy accesible. Precio reducido en lista.', ambiente: 'Club disco-house en Malasaña. Ambiente muy divertido y colorido.', reputacion: 'Buenos con artistas. Ambiente muy festivo y sin egos.', artistas: 'DJs de disco y funk nacionales e internacionales', contacto: 'info@mondodisko.com o Instagram', red_flag: '', consejo: 'Perfecto si haces disco, funk o nu-disco. Ambiente muy receptivo.', mejor: 'Viernes noche', instagram: '@mondodisko' },
  { id: 14, name: 'Bahnhof Oost', city: 'Madrid', country: 'España', area: 'Lavapiés', type: 'bar', genres: ['Techno', 'House', 'Experimental'], score: 7.6, cachet: '€30–100', aforo: '100', fundado: '2016', entrada_precio: 'Gratis', entrada_tipo: 'free', entrada_nota: 'Sin entrada. Bar alternativo de barrio.', ambiente: 'Bar alternativo en Lavapiés. Escena underground madrileña.', reputacion: 'Cachets bajos pero muy abiertos. Buenos para la escena local.', artistas: 'DJs emergentes del underground madrileño', contacto: 'Instagram @bahnhof_oost_madrid', red_flag: '', consejo: 'Ideal para hacer red en la escena underground de Madrid.', mejor: 'Jueves y viernes' },

  // ─────────────────────────────────────────────
  // BARCELONA
  // ─────────────────────────────────────────────
  { id: 15, name: 'Razzmatazz', city: 'Barcelona', country: 'España', area: 'Poblenou', type: 'club', genres: ['Indie', 'Techno', 'House', 'Pop'], score: 8.4, cachet: '€100–600', aforo: '3000', fundado: '2000', entrada_precio: '€10–20', entrada_tipo: 'mid', entrada_nota: '5 salas con música diferente. Precio variable según evento.', ambiente: '5 salas en antigua fábrica. La sala más grande de Barcelona.', reputacion: 'Muy profesionales. Buenos pagadores. Producción de primer nivel.', artistas: 'Variado — todos los géneros', contacto: 'booking@razzmatazz.com', red_flag: '', consejo: 'Presenta tu propuesta especificando en qué sala encajas mejor.', mejor: 'Viernes y sábado', website: 'salarazzmatazz.com' },
  { id: 16, name: 'Input Barcelona', city: 'Barcelona', country: 'España', area: 'Poble Sec', type: 'club', genres: ['Techno', 'House', 'Minimal'], score: 9.0, cachet: '€80–500', aforo: '500', fundado: '2015', entrada_precio: '€10–18', entrada_tipo: 'mid', entrada_nota: 'Sistema de sonido Funktion-One. Precio acorde a la calidad.', ambiente: 'El mejor sistema de sonido de Barcelona. Club serio y artístico.', reputacion: 'Excelentes condiciones para artistas. Muy respetados en la escena.', artistas: 'Surgeon, Paula Temple, Objekt', contacto: 'booking@inputbcn.com', red_flag: '', consejo: 'Si haces techno serio, este es tu objetivo en Barcelona.', mejor: 'Viernes y sábado', website: 'inputbcn.com' },
  { id: 17, name: 'Nitsa Club', city: 'Barcelona', country: 'España', area: 'Nou de la Rambla', type: 'club', genres: ['Techno', 'House', 'Electronic'], score: 8.7, cachet: '€70–400', aforo: '600', fundado: '1993', entrada_precio: '€8–15', entrada_tipo: 'low', entrada_nota: 'Veterano. Precio muy accesible para la calidad del lineup.', ambiente: 'Club histórico en sala Apolo. Uno de los más respetados de España.', reputacion: 'Institución. Pagan bien. Cuidan mucho la programación artística.', artistas: 'Dixon, Âme, Hunee, Job Jobse', contacto: 'info@nitsa.com', red_flag: '', consejo: 'Envía mix muy cuidado. Valoran la coherencia artística por encima de todo.', mejor: 'Sábado madrugada', website: 'nitsa.com' },
  { id: 18, name: 'Pacha Barcelona', city: 'Barcelona', country: 'España', area: 'Port Olímpic', type: 'club', genres: ['House', 'Commercial', 'Deep House'], score: 7.2, cachet: '€200–1000', aforo: '1500', fundado: '1979', entrada_precio: '€15–25', entrada_tipo: 'high', entrada_nota: 'Precio alto. Ambiente muy turístico y de lujo.', ambiente: 'Icono de la noche barcelonesa. Ambiente glamuroso y turístico.', reputacion: 'Buenos pagadores para DJs con nombre. Difícil para nuevos.', artistas: 'DJs internacionales de house y commercial', contacto: 'barcelona@pacha.com', red_flag: 'Muy comercial y caro. Para DJs de house mainstream.', consejo: 'Solo si tienes seguidores o nombre establecido en la escena comercial.', mejor: 'Viernes y sábado' },
  { id: 19, name: 'Moog Barcelona', city: 'Barcelona', country: 'España', area: 'Barrio Gótico', type: 'club', genres: ['Techno', 'Electronic', 'Industrial'], score: 8.2, cachet: '€50–250', aforo: '250', fundado: '1994', entrada_precio: '€7–12', entrada_tipo: 'low', entrada_nota: 'Club íntimo y accesible. Muy popular entre locales.', ambiente: 'Club pequeño y oscuro en el Barrio Gótico. Muy íntimo y underground.', reputacion: 'Buenos con artistas. Ambiente muy auténtico.', artistas: 'DJs de techno y electronic europeos', contacto: 'info@masimas.com (grupo Mas i Mas)', red_flag: '', consejo: 'Buena opción para DJs con estética underground. Envía mix oscuro.', mejor: 'Jueves y sábado' },

  // ─────────────────────────────────────────────
  // IBIZA
  // ─────────────────────────────────────────────
  { id: 20, name: 'DC-10', city: 'Ibiza', country: 'España', area: 'Playa den Bossa', type: 'club', genres: ['House', 'Techno', 'Organic'], score: 9.6, cachet: '€200–2000', aforo: '1200', fundado: '1999', entrada_precio: '€20–40', entrada_tipo: 'high', entrada_nota: 'Lunes es el día icónico (Circoloco). Precio alto en verano.', ambiente: 'El club más auténtico de Ibiza. Terrace legendaria al aire libre.', reputacion: 'Los mejores de la isla en trato a artistas. Contratos serios.', artistas: 'Seth Troxler, Loco Dice, The Martinez Brothers', contacto: 'booking@dc10ibiza.com', red_flag: '', consejo: 'Solo en verano (jun-oct). Necesitas representación o recomendación directa.', mejor: 'Lunes (Circoloco)', website: 'dc10ibiza.com' },
  { id: 21, name: 'Amnesia Ibiza', city: 'Ibiza', country: 'España', area: 'San Rafael', type: 'club', genres: ['House', 'Techno', 'Commercial'], score: 8.9, cachet: '€300–3000', aforo: '3000', fundado: '1976', entrada_precio: '€30–60', entrada_tipo: 'high', entrada_nota: 'Uno de los clubs más caros de Ibiza. Espectáculos visuales.', ambiente: 'Mega club histórico. La sala principal tiene el techo que se abre.', reputacion: 'Buenos pagadores para artistas con nombre. Producciones espectaculares.', artistas: 'Marco Carola, Luciano, Carl Cox', contacto: 'booking@amnesia.es', red_flag: 'Muy difícil para nuevos. Orientado a artistas establecidos.', consejo: 'Orientado a artistas con booking internacional. Necesitas agencia.', mejor: 'Martes y jueves (eventos residentes)', website: 'amnesia.es' },
  { id: 22, name: 'Pacha Ibiza', city: 'Ibiza', country: 'España', area: 'Ibiza Ciudad', type: 'club', genres: ['House', 'Commercial', 'Deep House'], score: 8.5, cachet: '€400–5000', aforo: '3000', fundado: '1973', entrada_precio: '€30–70', entrada_tipo: 'high', entrada_nota: 'El más icónico de Ibiza. Precios premium. VIP area importante.', ambiente: 'El club más famoso del mundo. Icono absoluto de la isla.', reputacion: 'Pagan muy bien a artistas establecidos. Contratos profesionales.', artistas: 'David Guetta, Solomun, Black Coffee', contacto: 'booking@pacha.com', red_flag: 'Solo para artistas con nombre internacional. Imposible para nuevos.', consejo: 'Target a largo plazo. Necesitas agencia consolidada y nombre propio.', mejor: 'Viernes (Solomun+1)', website: 'pacha.com' },
  { id: 23, name: 'Hï Ibiza', city: 'Ibiza', country: 'España', area: 'Playa den Bossa', type: 'club', genres: ['House', 'Techno', 'Commercial'], score: 8.7, cachet: '€300–4000', aforo: '2500', fundado: '2017', entrada_precio: '€25–55', entrada_tipo: 'high', entrada_nota: 'Club moderno con producción visual de primer nivel.', ambiente: 'El club más moderno de Ibiza. Tecnología visual avanzada.', reputacion: 'Muy profesionales. Buenos con artistas internacionales.', artistas: 'Eric Prydz, Tale Of Us, Fisher', contacto: 'booking@hiibiza.com', red_flag: 'Para artistas establecidos. Muy difícil para nuevos.', consejo: 'Necesitas agencia internacional. Target a largo plazo.', mejor: 'Miércoles (Eric Prydz) y domingos' },
  { id: 24, name: 'Benimussa Park', city: 'Ibiza', country: 'España', area: 'San Antonio', type: 'festival', genres: ['House', 'Techno', 'Organic'], score: 8.3, cachet: '€150–1500', aforo: '3000', fundado: '2010', entrada_precio: '€25–40', entrada_tipo: 'high', entrada_nota: 'Eventos open air. Precio varía según el evento.', ambiente: 'Recinto open air en finca. Eventos diurnos y nocturnos únicos.', reputacion: 'Buenos pagadores para artistas de house orgánico y afro.', artistas: 'Bedouin, Behrouz, Damian Lazarus', contacto: 'info@benimussapark.com', red_flag: '', consejo: 'Perfecto para house orgánico y afro. Ambiente único en Ibiza.', mejor: 'Temporada verano (jun-sep)' },

  // ─────────────────────────────────────────────
  // LONDRES
  // ─────────────────────────────────────────────
  { id: 25, name: 'Fabric', city: 'Londres', country: 'Reino Unido', area: 'Farringdon', type: 'club', genres: ['Techno', 'House', 'Drum & Bass'], score: 9.7, cachet: '€150–1000', aforo: '1500', fundado: '1999', entrada_precio: '£12–20', entrada_tipo: 'mid', entrada_nota: 'Precio estándar para Londres. Tres salas con géneros distintos.', ambiente: 'El club más importante de UK. Tres salas, sonido perfecto, sin compromiso.', reputacion: 'El mejor trato a artistas del mundo. Contratos impecables.', artistas: 'Craig Richards, Terry Francis, Skream', contacto: 'booking@fabriclondon.com', red_flag: '', consejo: 'La meta de cualquier DJ serio en UK. Necesitas reputación previa.', mejor: 'Viernes (Room Two) y sábado (Room One)', website: 'fabriclondon.com' },
  { id: 26, name: 'Printworks London', city: 'Londres', country: 'Reino Unido', area: 'Canada Water', type: 'club', genres: ['Techno', 'House', 'Electronic'], score: 9.1, cachet: '€200–1500', aforo: '2000', fundado: '2017', entrada_precio: '£15–25', entrada_tipo: 'mid', entrada_nota: 'Espacio único en antigua imprenta. Producción visual increíble.', ambiente: 'Espacio industrial único. Las mejores producciones visuales de Londres.', reputacion: 'Muy profesionales. Pagan bien. Producciones de primer nivel.', artistas: 'Helena Hauff, Peggy Gou, Aphex Twin', contacto: 'info@printworkslondon.com', red_flag: '', consejo: 'Busca eventos de promotores externos que alquilan el espacio.', mejor: 'Eventos especiales y temporada invierno' },
  { id: 27, name: 'Fold London', city: 'Londres', country: 'Reino Unido', area: 'Canning Town', type: 'club', genres: ['Techno', 'Experimental', 'Queer'], score: 8.6, cachet: '€80–400', aforo: '600', fundado: '2018', entrada_precio: '£10–18', entrada_tipo: 'mid', entrada_nota: 'Club queer-friendly. Muy respetado en la escena de Londres.', ambiente: 'Club underground queer en zona industrial. Muy community.', reputacion: 'Excelentes condiciones para artistas. Muy inclusivos y profesionales.', artistas: 'Objekt, Sherelle, Call Super', contacto: 'bookings@fold.london', red_flag: '', consejo: 'Ideal si tu música tiene componente queer o experimental.', mejor: 'Viernes y sábado' },
  { id: 28, name: 'Egg London', city: 'Londres', country: 'Reino Unido', area: 'Kings Cross', type: 'club', genres: ['House', 'Techno', 'Minimal'], score: 8.0, cachet: '€70–350', aforo: '800', fundado: '2003', entrada_precio: '£10–20', entrada_tipo: 'mid', entrada_nota: 'Abre 24h los fines de semana. Precio accesible para Londres.', ambiente: 'Club de 3 plantas con terrace en Kings Cross. Abierto 24h.', reputacion: 'Buenos pagadores. Abiertos a DJs internacionales.', artistas: 'Loco Dice, Francesca Lombardo, Archie Hamilton', contacto: 'booking@egglondon.net', red_flag: '', consejo: 'El formato 24h es ideal para DJs que quieren tocar en horario matinal.', mejor: 'Sábado noche – domingo tarde' },
  { id: 29, name: 'Corsica Studios', city: 'Londres', country: 'Reino Unido', area: 'Elephant & Castle', type: 'club', genres: ['Techno', 'Experimental', 'Electronic'], score: 8.4, cachet: '€50–300', aforo: '350', fundado: '2009', entrada_precio: '£8–15', entrada_tipo: 'low', entrada_nota: 'Precio accesible para Londres. Club underground con gran reputación.', ambiente: 'Club underground en dos salas. Escena muy artística y experimental.', reputacion: 'Muy respetados. Buenos con artistas emergentes con propuesta artística.', artistas: 'Actress, Batu, Nídia', contacto: 'bookings@corsicastudios.com', red_flag: '', consejo: 'Buena puerta de entrada en Londres si tienes propuesta artística sólida.', mejor: 'Viernes y sábado' },

  // ─────────────────────────────────────────────
  // AMSTERDAM
  // ─────────────────────────────────────────────
  { id: 30, name: 'De School', city: 'Amsterdam', country: 'Países Bajos', area: 'Geuzenveld', type: 'club', genres: ['Techno', 'House', 'Experimental'], score: 9.3, cachet: '€100–600', aforo: '700', fundado: '2016', entrada_precio: '€12–18', entrada_tipo: 'mid', entrada_nota: 'Cerrado en 2018. Referencia histórica de la escena de Amsterdam.', ambiente: 'Antiguo colegio convertido en club. Escena artística y musical única.', reputacion: 'Fue el estándar de la industria en Amsterdam. Legado enorme.', artistas: 'Call Super, Palms Trax, Hunee', contacto: 'Cerrado permanentemente en 2018.', red_flag: 'Ya no existe. Incluido como referencia histórica.', consejo: 'Investiga los ex-residentes que ahora programan en otros clubs de la ciudad.', mejor: 'N/A (cerrado)' },
  { id: 31, name: 'Shelter Amsterdam', city: 'Amsterdam', country: 'Países Bajos', area: 'Overtoom', type: 'club', genres: ['Techno', 'House', 'Electronic'], score: 8.5, cachet: '€80–400', aforo: '500', fundado: '2015', entrada_precio: '€10–16', entrada_tipo: 'mid', entrada_nota: 'Club subterráneo bajo una piscina. Ambiente muy especial.', ambiente: 'Club bajo una piscina olímpica. Acústica increíble y ambiente único.', reputacion: 'Muy profesionales. Buenos pagadores para artistas con propuesta.', artistas: 'Identified Patient, Dj Stingray, Kode9', contacto: 'booking@shelteramsterdam.nl', red_flag: '', consejo: 'Envía propuesta artística sólida. Valoran la coherencia.', mejor: 'Viernes y sábado', website: 'shelteramsterdam.nl' },
  { id: 32, name: 'Paradiso Amsterdam', city: 'Amsterdam', country: 'Países Bajos', area: 'Leidseplein', type: 'club', genres: ['House', 'Electronic', 'Live'], score: 8.8, cachet: '€100–800', aforo: '1500', fundado: '1968', entrada_precio: '€12–25', entrada_tipo: 'mid', entrada_nota: 'Iglesia convertida en sala de conciertos y club. Icónica.', ambiente: 'Iglesia convertida. Icono cultural de Amsterdam. Muy variado.', reputacion: 'Institución. Excelentes condiciones para artistas.', artistas: 'Bicep, Jon Hopkins, Four Tet', contacto: 'booking@paradiso.nl', red_flag: '', consejo: 'Más orientado a actuaciones en directo. Bueno para DJ sets con componente live.', mejor: 'Eventos especiales y fines de semana', website: 'paradiso.nl' },
  { id: 33, name: 'Thuishaven', city: 'Amsterdam', country: 'Países Bajos', area: 'Zeeburg', type: 'festival', genres: ['House', 'Techno', 'Afro'], score: 8.2, cachet: '€80–500', aforo: '2000', fundado: '2014', entrada_precio: '€15–25', entrada_tipo: 'mid', entrada_nota: 'Festival open air. Solo temporada verano.', ambiente: 'Festival en puerto industrial. Eventos open air con varios stages.', reputacion: 'Buenos pagadores. Gran ambiente de comunidad.', artistas: 'Antal, Hunee, Red Axes', contacto: 'info@thuishaven.com', red_flag: '', consejo: 'Perfecto para house y afro. Muy community y artístico.', mejor: 'Temporada verano' },

  // ─────────────────────────────────────────────
  // PARÍS
  // ─────────────────────────────────────────────
  { id: 34, name: 'Rex Club', city: 'París', country: 'Francia', area: 'Grands Boulevards', type: 'club', genres: ['Techno', 'House', 'Electronic'], score: 9.0, cachet: '€80–500', aforo: '500', fundado: '1990', entrada_precio: '€12–18', entrada_tipo: 'mid', entrada_nota: 'Institución del techno en París. Precio estándar francés.', ambiente: 'El club de techno más legendario de París. Sonido Laurent Garnier.', reputacion: 'Institución. Muy respetados. Buen trato a artistas.', artistas: 'Laurent Garnier, Miss Kittin, DJ Hell', contacto: 'booking@rexclub.com', red_flag: '', consejo: 'La referencia del techno en París. Envía mix técnico y con visión artística.', mejor: 'Viernes y sábado', website: 'rexclub.com' },
  { id: 35, name: 'Concrete Paris', city: 'París', country: 'Francia', area: 'Quai de la Rapée', type: 'club', genres: ['Techno', 'House', 'Experimental'], score: 8.8, cachet: '€80–450', aforo: '600', fundado: '2011', entrada_precio: '€12–20', entrada_tipo: 'mid', entrada_nota: 'Abre 24h. Barco en el Sena convertido en club.', ambiente: 'Club en barco en el Sena. Abierto 24h. Escena artística potente.', reputacion: 'Muy profesionales. Buenos con artistas europeos emergentes.', artistas: 'Dj Stingray, Paula Temple, Surgeon', contacto: 'booking@concreteparis.fr', red_flag: '', consejo: 'El Fabric de París. Necesitas reputación en la escena europea.', mejor: 'Viernes – sábado 24h', website: 'concreteparis.fr' },
  { id: 36, name: 'Badaboum', city: 'París', country: 'Francia', area: 'Bastille', type: 'club', genres: ['House', 'Disco', 'Electronic'], score: 7.8, cachet: '€60–300', aforo: '400', fundado: '2012', entrada_precio: '€8–15', entrada_tipo: 'low', entrada_nota: 'Precio accesible para París. Buena relación calidad-precio.', ambiente: 'Club en Bastille. Muy popular entre la escena artística parisina.', reputacion: 'Buenos pagadores. Abiertos a propuestas nuevas.', artistas: 'DJs de house y disco europeos', contacto: 'booking@badaboum.fr', red_flag: '', consejo: 'Buena puerta de entrada al circuito de París. Envía mix de house.', mejor: 'Viernes y sábado' },
  { id: 37, name: 'Social Club Paris', city: 'París', country: 'Francia', area: 'Grands Boulevards', type: 'club', genres: ['Hip-Hop', 'Electronic', 'House'], score: 7.5, cachet: '€50–250', aforo: '350', fundado: '2009', entrada_precio: '€8–12', entrada_tipo: 'low', entrada_nota: 'Club ecléctico con programación muy variada.', ambiente: 'Club ecléctico y cultural. Mezcla hip-hop, electrónica y arte.', reputacion: 'Buenos con artistas diversos. Ambiente muy creativo.', artistas: 'Flying Lotus, Com Truise, Nosaj Thing', contacto: 'booking@socialclubparis.com', red_flag: '', consejo: 'Ideal si haces electrónica con influencias hip-hop o experimental.', mejor: 'Jueves y viernes' },

  // ─────────────────────────────────────────────
  // LISBOA
  // ─────────────────────────────────────────────
  { id: 38, name: 'Lux Frágil', city: 'Lisboa', country: 'Portugal', area: 'Santa Apolónia', type: 'club', genres: ['House', 'Techno', 'Electronic'], score: 9.1, cachet: '€80–500', aforo: '800', fundado: '1998', entrada_precio: '€10–18', entrada_tipo: 'mid', entrada_nota: 'El mejor club de Lisboa. Precio justo para la calidad.', ambiente: 'El club más icónico de Portugal. Orillas del Tajo. Terrace con vistas.', reputacion: 'Institución. Pagan bien y trato excelente a artistas.', artistas: 'Laurent Garnier, Ricardo Villalobos, Joakim', contacto: 'booking@luxfragil.com', red_flag: '', consejo: 'La referencia en Lisboa. Envía propuesta artística seria con mix.', mejor: 'Jueves, viernes y sábado', website: 'luxfragil.com' },
  { id: 39, name: 'Village Underground Lisboa', city: 'Lisboa', country: 'Portugal', area: 'Alcântara', type: 'club', genres: ['Electronic', 'House', 'Indie'], score: 8.0, cachet: '€60–300', aforo: '500', fundado: '2014', entrada_precio: '€8–15', entrada_tipo: 'low', entrada_nota: 'Espacio cultural en vagones de tren. Ambiente muy creativo.', ambiente: 'Vagones de tren convertidos en club y espacio cultural. Único.', reputacion: 'Buenos con artistas creativos. Ambiente muy artístico.', artistas: 'DJs europeos de house y electronic', contacto: 'booking@vulisboa.com', red_flag: '', consejo: 'Perfecto para artistas con propuesta visual y artística.', mejor: 'Viernes y sábado' },
  { id: 40, name: 'Music Box Lisboa', city: 'Lisboa', country: 'Portugal', area: 'Cais do Sodré', type: 'club', genres: ['Indie', 'Electronic', 'House'], score: 7.7, cachet: '€50–250', aforo: '400', fundado: '2006', entrada_precio: '€7–12', entrada_tipo: 'low', entrada_nota: 'Precio muy accesible. Zona de Cais do Sodré muy activa.', ambiente: 'Club popular en zona de bares. Mezcla indie, electrónica y live.', reputacion: 'Buenos con nuevos artistas. Ambiente muy abierto.', artistas: 'DJs locales y europeos emergentes', contacto: 'info@musicbox-lisboa.com', red_flag: '', consejo: 'Buena puerta de entrada en Lisboa. Ambiente muy receptivo con nuevos DJs.', mejor: 'Viernes y sábado' },
  { id: 41, name: 'Ministerium Club', city: 'Lisboa', country: 'Portugal', area: 'Baixa', type: 'club', genres: ['Techno', 'House', 'Minimal'], score: 7.9, cachet: '€50–280', aforo: '350', fundado: '2018', entrada_precio: '€8–15', entrada_tipo: 'low', entrada_nota: 'Club subterráneo en el centro histórico.', ambiente: 'Club subterráneo con estética industrial. Escena techno seria.', reputacion: 'Buenos pagadores para su tamaño. Abiertos a DJs europeos.', artistas: 'DJs de techno y minimal europeos', contacto: 'booking@ministeriumclub.com', red_flag: '', consejo: 'Si haces techno minimal o industrial, encaja perfectamente aquí.', mejor: 'Viernes y sábado' },

  // ─────────────────────────────────────────────
  // MILÁN
  // ─────────────────────────────────────────────
  { id: 42, name: 'Palazzo Reale / Volt Club', city: 'Milán', country: 'Italia', area: 'Navigli', type: 'club', genres: ['Techno', 'House', 'Electronic'], score: 8.3, cachet: '€80–400', aforo: '600', fundado: '2015', entrada_precio: '€10–18', entrada_tipo: 'mid', entrada_nota: 'Club moderno en zona Navigli. Precio estándar milanés.', ambiente: 'Club de diseño en zona Navigli. Estética muy italiana y refinada.', reputacion: 'Buenos pagadores. Muy profesionales en la organización.', artistas: 'DJs de techno y house europeos', contacto: 'booking@voltmilano.com', red_flag: '', consejo: 'La escena de Milán es muy fashion. Cuida también tu imagen artística.', mejor: 'Viernes y sábado' },
  { id: 43, name: 'Plastic Milano', city: 'Milán', country: 'Italia', area: 'Porta Venezia', type: 'club', genres: ['House', 'Disco', 'Queer'], score: 8.5, cachet: '€70–350', aforo: '400', fundado: '1980', entrada_precio: '€10–20', entrada_tipo: 'mid', entrada_nota: 'Histórico club queer de Milán. Ambiente muy fashion.', ambiente: 'Club histórico queer. Icono de la noche y la moda en Milán.', reputacion: 'Institución. Pagan bien. Ambiente muy fashion y artístico.', artistas: 'DJs de house y disco internacionales', contacto: 'info@plastico.it', red_flag: '', consejo: 'Perfecto si haces house o disco con estética fashion o queer.', mejor: 'Viernes y sábado', website: 'plastico.it' },
  { id: 44, name: 'Tunnel Milano', city: 'Milán', country: 'Italia', area: 'Porta Garibaldi', type: 'club', genres: ['Techno', 'Industrial', 'EBM'], score: 8.1, cachet: '€60–300', aforo: '500', fundado: '2003', entrada_precio: '€8–15', entrada_tipo: 'low', entrada_nota: 'Club en túnel subterráneo. Escena techno muy dura.', ambiente: 'Literalmente un túnel subterráneo. Techno oscuro e industrial.', reputacion: 'Buenos con artistas de techno duro. Ambiente muy auténtico.', artistas: 'Ancient Methods, Phase, Rebekah', contacto: 'info@tunnelmilano.com', red_flag: '', consejo: 'Solo si haces techno industrial o muy oscuro. No apto para house.', mejor: 'Sábado' },
  { id: 45, name: 'Magnolia Milano', city: 'Milán', country: 'Italia', area: 'Segrate', type: 'club', genres: ['House', 'Techno', 'Mixed'], score: 7.6, cachet: '€60–280', aforo: '800', fundado: '1999', entrada_precio: '€8–15', entrada_tipo: 'low', entrada_nota: 'Club open air en verano. Muy popular entre jóvenes milaneses.', ambiente: 'Club open air estival. Muy popular y con buena programación.', reputacion: 'Buenos pagadores para su tamaño. Muy abiertos a propuestas.', artistas: 'DJs locales e internacionales de house y techno', contacto: 'booking@magnoliaclub.it', red_flag: '', consejo: 'Buena puerta de entrada en Milán. Ambiente muy receptivo.', mejor: 'Temporada verano (jun-sep)' },

  // ─────────────────────────────────────────────
  // FESTIVALES EUROPEOS
  // ─────────────────────────────────────────────
  { id: 46, name: 'Sonar Festival', city: 'Barcelona', country: 'España', area: 'Fira Barcelona', type: 'festival', genres: ['Electronic', 'Techno', 'Experimental', 'Live'], score: 9.5, cachet: '€200–5000', aforo: '120000', fundado: '1994', entrada_precio: '€50–200', entrada_tipo: 'high', entrada_nota: 'Festival de 3 días. Day y Night pass por separado.', ambiente: 'El festival de música electrónica más importante del mundo hispano.', reputacion: 'Institución mundial. Pagan muy bien. Producciones de primer nivel.', artistas: 'Aphex Twin, Bicep, Four Tet, Björk', contacto: 'booking@sonar.es', red_flag: '', consejo: 'Necesitas agencia internacional consolidada. Target a largo plazo.', mejor: 'Junio', website: 'sonar.es' },
  { id: 47, name: 'Dekmantel Festival', city: 'Amsterdam', country: 'Países Bajos', area: 'Amsterdamse Bos', type: 'festival', genres: ['House', 'Techno', 'Experimental'], score: 9.4, cachet: '€200–3000', aforo: '15000', fundado: '2012', entrada_precio: '€40–120', entrada_tipo: 'high', entrada_nota: 'Festival de 3 días en el bosque. Entradas se agotan en minutos.', ambiente: 'El festival de culto del house y techno europeo. En el bosque de Amsterdam.', reputacion: 'Los mejores de Europa en cuidar la programación artística.', artistas: 'Hunee, Antal, Call Super, Objekt', contacto: 'booking@dekmantelfestival.com', red_flag: '', consejo: 'Muy selectivo. Prioriza DJs con propuesta artística única.', mejor: 'Agosto', website: 'dekmantelfestival.com' },
  { id: 48, name: 'Boiler Room (eventos)', city: 'Múltiples ciudades', country: 'Europa', area: 'Varios', type: 'festival', genres: ['House', 'Techno', 'Grime', 'Experimental'], score: 9.2, cachet: '€100–2000', aforo: '500', fundado: '2010', entrada_precio: 'Gratis (lista)', entrada_tipo: 'free', entrada_nota: 'Invitación por lista. Contenido transmitido online a millones.', ambiente: 'Eventos de streaming en vivo. Enorme visibilidad online global.', reputacion: 'Excelente para visibilidad. Pagan correcto. Muy profesionales.', artistas: 'Todos los grandes de la escena electrónica mundial', contacto: 'booking@boilerroom.tv', red_flag: '', consejo: 'Un Boiler Room puede cambiar tu carrera. Necesitas recomendación de alguien dentro.', mejor: 'Todo el año en distintas ciudades', website: 'boilerroom.tv' },
  { id: 49, name: 'Movement Festival', city: 'Berlín', country: 'Alemania', area: 'Kraftwerk', type: 'festival', genres: ['Techno', 'Electronic', 'Experimental'], score: 8.9, cachet: '€150–2000', aforo: '5000', fundado: '2012', entrada_precio: '€25–60', entrada_tipo: 'high', entrada_nota: 'Festival de techno en Kraftwerk Berlin. Enero cada año.', ambiente: 'Festival de techno en el espacio industrial de Kraftwerk. Único.', reputacion: 'Muy profesionales. Buenos pagadores para artistas de techno.', artistas: 'Ben Klock, DVS1, Surgeon', contacto: 'booking@movement.de', red_flag: '', consejo: 'Si haces techno serio, es uno de los mejores festivales de invierno.', mejor: 'Enero', website: 'movement.de' },
  { id: 50, name: 'Time Warp', city: 'Mannheim', country: 'Alemania', area: 'Maimarktgelände', type: 'festival', genres: ['Techno', 'House', 'Minimal'], score: 9.0, cachet: '€200–3000', aforo: '15000', fundado: '1994', entrada_precio: '€35–80', entrada_tipo: 'high', entrada_nota: 'Festival de 2 días. Uno de los más longevos de Europa.', ambiente: 'Festival indoor de techno. Producción visual de primer nivel.', reputacion: 'Institución. Pagan muy bien. Producciones espectaculares.', artistas: 'Richie Hawtin, Sven Väth, Chris Liebing', contacto: 'booking@time-warp.de', red_flag: '', consejo: 'Necesitas nombre establecido en la escena techno europea.', mejor: 'Marzo/Abril', website: 'time-warp.de' },
]

// Utilidades
export const CITIES = [...new Set(VENUES_DB.map(v => v.city))].sort()
export const COUNTRIES = [...new Set(VENUES_DB.map(v => v.country))].sort()

export function getVenuesByCity(city: string): VenueDB[] {
  return VENUES_DB.filter(v => v.city === city)
}

export function getVenuesByType(type: VenueDB['type']): VenueDB[] {
  return VENUES_DB.filter(v => v.type === type)
}

export function searchVenues(query: string): VenueDB[] {
  const q = query.toLowerCase()
  return VENUES_DB.filter(v =>
    v.name.toLowerCase().includes(q) ||
    v.city.toLowerCase().includes(q) ||
    v.genres.some(g => g.toLowerCase().includes(q)) ||
    v.area.toLowerCase().includes(q)
  )
}

export const VENUE_STATS = {
  total: VENUES_DB.length,
  clubs: VENUES_DB.filter(v => v.type === 'club').length,
  bars: VENUES_DB.filter(v => v.type === 'bar').length,
  festivals: VENUES_DB.filter(v => v.type === 'festival').length,
  cities: CITIES.length,
}
